// This file is automatically generated based on the Looker Core API metadata.

export interface AccessToken {
  /** Access Token used for API calls */
  access_token: string | null
  /** Type of Token */
  token_type: string | null
  /** Number of seconds before the token expires */
  expires_in: number | null
}

export interface RequestAccessToken {

}
