// This file is automatically generated based on the Looker Core API metadata.

export interface AlertNotification {
  method: string | null
  style: string | null
  minute: string[] | null
  hour: string[] | null
  day_of_month: string[] | null
  month: string[] | null
  day_of_week: string[] | null
}

export interface RequestAlertNotification {
  method?: string | null
  style?: string | null
  minute?: string[] | null
  hour?: string[] | null
  day_of_month?: string[] | null
  month?: string[] | null
  day_of_week?: string[] | null
}
