// This file is automatically generated based on the Looker Core API metadata.

export interface AlertThreshold {
  /** Value of the alert threshold */
  value: number
}

export interface RequestAlertThreshold {
  /** Value of the alert threshold */
  value?: number
}
