// This file is automatically generated based on the Looker Core API metadata.

export interface AlertAppliedDashboardFilter {
  /** Field Title */
  filter_title: string | null
  /** Field Name */
  field_name: string
  /** Field Value */
  filter_value: string
  /** Filter Description */
  filter_description: string | null
}

export interface RequestAlertAppliedDashboardFilter {
  /** Field Title */
  filter_title?: string | null
  /** Field Name */
  field_name?: string
  /** Field Value */
  filter_value?: string
  /** Filter Description */
  filter_description?: string | null
}
