// This file is automatically generated based on the Looker Core API metadata.

export interface AlertChangeOwnerRequest {
  /** ID of the new owner */
  user_id: number
}

export interface RequestAlertChangeOwnerRequest {
  /** ID of the new owner */
  user_id?: number
}
