// This file is automatically generated based on the Looker Core API metadata.

export interface AlertOptions {
  /** Reasons an alert created on the specified query wouldn't be followable. */
  reasons_query_is_unfollowable: string[]
}

export interface RequestAlertOptions {
  /** Reasons an alert created on the specified query wouldn't be followable. */
  reasons_query_is_unfollowable?: string[]
}
