// This file is automatically generated based on the Looker Core API metadata.

export interface AlertFieldFilter {
  /** Field Name */
  field_name: string
  /** Field Value */
  field_value: string
  /** Filter Value */
  filter_value: string | null
}

export interface RequestAlertFieldFilter {
  /** Field Name */
  field_name?: string
  /** Field Value */
  field_value?: string
  /** Filter Value */
  filter_value?: string | null
}
