// This file is automatically generated based on the Looker Core API metadata.

export interface ApiVersionElement {
  /** Version number as it appears in '/api/xxx/' urls */
  version: string | null
  /** Full version number including minor version */
  full_version: string | null
  /** Status of this version */
  status: string | null
  /** Url for swagger.json for this version */
  swagger_url: string | null
}

export interface RequestApiVersionElement {

}
