// This file is automatically generated based on the Looker Core API metadata.

import { ApiVersionElement } from './api_version_element'

export interface ApiVersion {
  /** Current Looker release version number */
  looker_release_version: string | null
  /** Current version for this Looker instance */
  current_version: ApiVersionElement | null
  /** Array of versions supported by this Looker instance */
  supported_versions: ApiVersionElement[] | null
}

export interface RequestApiVersion {

}
