// This file is automatically generated based on the Looker Core API metadata.

export interface ApiSession {
  /** Operations the current user is able to perform on this object */
  can: {[key: string]: boolean}
  /** The id of active workspace for this session */
  workspace_id: string | null
  /** The id of the actual user in the case when this session represents one user sudo'ing as another */
  sudo_user_id: number | null
}

export interface RequestApiSession {
  /** The id of active workspace for this session */
  workspace_id?: string | null
}
