// This file is automatically generated based on the Looker Core API metadata.

import { Ability } from './ability'
import { AppStateProject } from './app_state_project'
import { ThinDataApp } from './thin_data_app'

export interface AppState {
  adminDefaultColorCollection: string | null
  adminDefaultColors: any | null
  allowPublicURLs: boolean
  allowTrendLines: boolean
  allowUserTimezones: boolean
  applicationTimezone: string | null
  closedSystem: boolean
  clustered: boolean
  conditionalAlerts: boolean
  connection_hub_enabled: boolean
  contentUsageEpoch: any | null
  curated_search_enabled: boolean
  currentAbility: Ability | null
  currentFile: any | null
  currentUser: any | null
  customColorCollections: any[] | null
  customMessagingExploreUrl: string | null
  customMessagingGlobalUrl: string | null
  customVisualizations: any | null
  dataApps: ThinDataApp[] | null
  defaultExportFormat: string | null
  defaultNamedValueFormats: any | null
  exportFormats: any | null
  feAssets: any | null
  firstAppVersion: any | null
  flash: any | null
  hostUrl: string | null
  internal_help_enabled: boolean
  internal_help_organization_name: string | null
  isDeveloperMode: boolean
  isLocalDevelopmentEnvironment: boolean
  isSelfSignedCert: boolean
  isSudoing: boolean
  layout: string | null
  legacy_feature_count: number | null
  legacy_locale_file: boolean
  legacy_ide_folders_toggle: boolean
  lexpEnabled: boolean
  logging_to_file: boolean
  new_dashboards: boolean
  number_format: string | null
  passwordRequirements: string | null
  pendoConfig: any | null
  project_max_browser_display_size: number | null
  project_max_upload_file_size: number | null
  project: any | null
  projectImport: boolean
  projectManifestFileName: string | null
  projects: AppStateProject[] | null
  queryLimitSettings: any | null
  rendering: boolean
  report_frontend_errors: boolean
  run_as_recipient: boolean
  session_settings: any | null
  showCookieConsentBanner: boolean
  showExternalHelpLinks: boolean
  siteLogoURL: string | null
  slackIntegration: boolean
  sql_runner_vis: boolean
  subtotals: boolean
  sudoer: any | null
  sudoerIsLookerEmployee: any | null
  useGravatar: boolean
  validS3Regions: any | null
  versionDocumentationLinkTarget: string | null
  versionForDocumentation: string | null
  versionForPresentationToUsers: string | null
  whitelabel: any | null
  zopim_settings: any | null
}

export interface RequestAppState {

}
