// This file is automatically generated based on the Looker Core API metadata.

export interface AppStateProject {
  /** Project Id */
  id: string
  /** Project Name (use id instead) */
  name: string | null
  /** Is example */
  is_example: boolean
  /** Is managed by marketplace */
  managed: boolean
  /** Is auxillary project managed by marketplace */
  managed_auxiliary: boolean
}

export interface RequestAppStateProject {

}
