// This file is automatically generated based on the Looker Core API metadata.

export interface AsyncQuery {
  /** Unique Id */
  query_task_id: string | null
  /** Estimated Runtime */
  runtime: number | null
}

export interface RequestAsyncQuery {

}
