// This file is automatically generated based on the Looker Core API metadata.

export interface BackupConfiguration {
  /** Operations the current user is able to perform on this object */
  can: {[key: string]: boolean}
  /** Type of backup: looker-s3 or custom-s3 */
  type: string | null
  /** Name of bucket for custom-s3 backups */
  custom_s3_bucket: string | null
  /** Name of region where the bucket is located */
  custom_s3_bucket_region: string | null
  /** Link to get this item */
  url: string | null
}

export interface RequestBackupConfiguration {
  /** Type of backup: looker-s3 or custom-s3 */
  type?: string | null
  /** Name of bucket for custom-s3 backups */
  custom_s3_bucket?: string | null
  /** Name of region where the bucket is located */
  custom_s3_bucket_region?: string | null
  /** (Write-Only) AWS S3 key used for custom-s3 backups */
  custom_s3_key?: string | null
  /** (Write-Only) AWS S3 secret used for custom-s3 backups */
  custom_s3_secret?: string | null
}
