// This file is automatically generated based on the Looker Core API metadata.

import { ContinuousPalette, RequestContinuousPalette } from './continuous_palette'
import { DiscretePalette, RequestDiscretePalette } from './discrete_palette'

export interface ColorCollection {
  /** Unique Id */
  id: string
  /** Label of color collection */
  label: string
  /** Array of categorical palette definitions */
  categoricalPalettes: DiscretePalette[]
  /** Array of discrete palette definitions */
  sequentialPalettes: ContinuousPalette[]
  /** Array of diverging palette definitions */
  divergingPalettes: ContinuousPalette[]
}

export interface RequestColorCollection {
  /** Label of color collection */
  label?: string
  /** Array of categorical palette definitions */
  categoricalPalettes?: RequestDiscretePalette[]
  /** Array of discrete palette definitions */
  sequentialPalettes?: RequestContinuousPalette[]
  /** Array of diverging palette definitions */
  divergingPalettes?: RequestContinuousPalette[]
}
