// This file is automatically generated based on the Looker Core API metadata.

export interface ColorStop {
  /** CSS color string */
  color: string
  /** Offset in continuous palette (0 to 100) */
  offset: number
}

export interface RequestColorStop {
  /** CSS color string */
  color?: string
  /** Offset in continuous palette (0 to 100) */
  offset?: number
}
