// This file is automatically generated based on the Looker Core API metadata.

export interface Commit {
  /** Operations the current user is able to perform on this object */
  can: {[key: string]: boolean}
  author: string | null
  author_email: string | null
  committer: string | null
  committer_email: string | null
  message: string | null
  sha: string | null
  time: string | null
  author_image: string | null
  committer_image: string | null
  service_url: string | null
}

export interface RequestCommit {

}
