// This file is automatically generated based on the Looker Core API metadata.

import { ContentValidatorError } from './content_validator_error'

export interface ContentValidation {
  /** A list of content errors */
  content_with_errors: ContentValidatorError[] | null
  /** Duration of content validation in seconds */
  computation_time: number | null
  /** The number of looks validated */
  total_looks_validated: number | null
  /** The number of dashboard elements validated */
  total_dashboard_elements_validated: number | null
  /** The number of explores used across all content validated */
  total_explores_validated: number | null
}

export interface RequestContentValidation {

}
