// This file is automatically generated based on the Looker Core API metadata.

import { ContentValidationDashboard } from './content_validation_dashboard'
import { ContentValidationDashboardElement } from './content_validation_dashboard_element'
import { ContentValidationDashboardFilter } from './content_validation_dashboard_filter'
import { ContentValidationError } from './content_validation_error'
import { ContentValidationLook } from './content_validation_look'

export interface ContentValidatorError {
  look: ContentValidationLook | null
  dashboard: ContentValidationDashboard | null
  dashboard_element: ContentValidationDashboardElement | null
  dashboard_filter: ContentValidationDashboardFilter | null
  /** A list of errors found for this piece of content */
  errors: ContentValidationError[] | null
  /** An id unique to this piece of content for this validation run */
  id: string
}

export interface RequestContentValidatorError {

}
