// This file is automatically generated based on the Looker Core API metadata.

export interface ContentView {
  /** Operations the current user is able to perform on this object */
  can: {[key: string]: boolean}
  /** Unique Id */
  id: number
  /** Id of viewed Look */
  look_id: number | null
  /** Id of the viewed Dashboard */
  dashboard_id: number | null
  /** Content metadata id of the Look or Dashboard */
  content_metadata_id: number | null
  /** Id of user content was viewed by */
  user_id: number | null
  /** Id of group content was viewed by */
  group_id: number | null
  /** Number of times piece of content was viewed */
  view_count: number | null
  /** Number of times piece of content was favorited */
  favorite_count: number | null
  /** Date the piece of content was last viewed */
  last_viewed_at: string | null
  /** Week start date for the view and favorite count during that given week */
  start_of_week_date: string | null
}

export interface RequestContentView {

}
