// This file is automatically generated based on the Looker Core API metadata.

import { ColorStop, RequestColorStop } from './color_stop'

export interface ContinuousPalette {
  /** Unique identity string */
  id: string
  /** Label for palette */
  label: string | null
  /** Type of palette */
  type: string
  /** Array of ColorStops in the palette */
  stops: ColorStop[]
}

export interface RequestContinuousPalette {
  /** Label for palette */
  label?: string | null
  /** Type of palette */
  type?: string
  /** Array of ColorStops in the palette */
  stops?: RequestColorStop[]
}
