// This file is automatically generated based on the Looker Core API metadata.

export interface ContentMeta {
  /** Operations the current user is able to perform on this object */
  can: {[key: string]: boolean}
  /** Unique Id */
  id: number
  /** Name or title of underlying content */
  name: string | null
  /** Id of Parent Content */
  parent_id: number | null
  /** Id of associated space when content_type is "space" */
  space_id: string | null
  /** Id of associated folder when content_type is "space" */
  folder_id: string | null
  /** Id of associated dashboard when content_type is "dashboard" */
  dashboard_id: string | null
  /** Id of associated look when content_type is "look" */
  look_id: number | null
  /** Content Type ("dashboard", "look", or "space") */
  content_type: string | null
  /** Whether content inherits its access levels from parent */
  inherits: boolean
  /** Id of Inherited Content */
  inheriting_id: number | null
  /** Content Slug */
  slug: string | null
}

export interface RequestContentMeta {
  /** Whether content inherits its access levels from parent */
  inherits?: boolean
}
