// This file is automatically generated based on the Looker Core API metadata.

export interface ContentValidationDashboardElement {
  /** Text tile body text */
  body_text: string | null
  /** Id of Dashboard */
  dashboard_id: string | null
  /** Unique Id */
  id: string
  /** Id Of Look */
  look_id: string | null
  /** Note Display */
  note_display: string | null
  /** Note State */
  note_state: string | null
  /** Note Text */
  note_text: string | null
  /** Note Text as Html */
  note_text_as_html: string | null
  /** Id Of Query */
  query_id: number | null
  /** Text tile subtitle text */
  subtitle_text: string | null
  /** Title of dashboard element */
  title: string | null
  /** Whether title is hidden */
  title_hidden: boolean
  /** Text tile title */
  title_text: string | null
  /** Type */
  type: string | null
}

export interface RequestContentValidationDashboardElement {
  /** Text tile body text */
  body_text?: string | null
  /** Id of Dashboard */
  dashboard_id?: string | null
  /** Id Of Look */
  look_id?: string | null
  /** Note Display */
  note_display?: string | null
  /** Note State */
  note_state?: string | null
  /** Note Text */
  note_text?: string | null
  /** Id Of Query */
  query_id?: number | null
  /** Text tile subtitle text */
  subtitle_text?: string | null
  /** Title of dashboard element */
  title?: string | null
  /** Whether title is hidden */
  title_hidden?: boolean
  /** Text tile title */
  title_text?: string | null
  /** Type */
  type?: string | null
}
