// This file is automatically generated based on the Looker Core API metadata.

export interface ContentValidationFolder {
  /** Unique Name */
  name: string
  /** Unique Id */
  id: string
}

export interface RequestContentValidationFolder {
  /** Unique Name */
  name?: string
}
