// This file is automatically generated based on the Looker Core API metadata.

export interface ContentValidationError {
  /** Error message */
  message: string | null
  /** Name of the field involved in the error */
  field_name: string | null
  /** Name of the model involved in the error */
  model_name: string | null
  /** Name of the explore involved in the error */
  explore_name: string | null
  /** Whether this validation error is removable */
  removable: boolean
}

export interface RequestContentValidationError {

}
