// This file is automatically generated based on the Looker Core API metadata.

export interface ContentValidationDashboardFilter {
  /** Unique Id */
  id: string
  /** Id of Dashboard */
  dashboard_id: string | null
  /** Name of filter */
  name: string | null
  /** Title of filter */
  title: string | null
  /** Type of filter: one of date, number, string, or field */
  type: string | null
  /** Default value of filter */
  default_value: string | null
  /** Model of filter (required if type = field) */
  model: string | null
  /** Explore of filter (required if type = field) */
  explore: string | null
  /** Dimension of filter (required if type = field) */
  dimension: string | null
}

export interface RequestContentValidationDashboardFilter {
  /** Name of filter */
  name?: string | null
  /** Title of filter */
  title?: string | null
  /** Type of filter: one of date, number, string, or field */
  type?: string | null
  /** Default value of filter */
  default_value?: string | null
  /** Model of filter (required if type = field) */
  model?: string | null
  /** Explore of filter (required if type = field) */
  explore?: string | null
  /** Dimension of filter (required if type = field) */
  dimension?: string | null
}
