// This file is automatically generated based on the Looker Core API metadata.

import { ContentValidationFolder } from './content_validation_folder'
import { ContentValidationSpace } from './content_validation_space'

export interface ContentValidationDashboard {
  /** Description */
  description: string | null
  /** Unique Id */
  id: string
  /** Space */
  space: ContentValidationSpace | null
  /** Folder */
  folder: ContentValidationFolder | null
  /** Dashboard Title */
  title: string | null
}

export interface RequestContentValidationDashboard {
  /** Description */
  description?: string | null
  /** Dashboard Title */
  title?: string | null
}
