// This file is automatically generated based on the Looker Core API metadata.

export interface ContentValidationSpace {
  /** Unique Name */
  name: string
  /** Unique Id */
  id: string
}

export interface RequestContentValidationSpace {
  /** Unique Name */
  name?: string
}
