// This file is automatically generated based on the Looker Core API metadata.

export interface ContentNavigation {
  /** Operations the current user is able to perform on this object */
  can: {[key: string]: boolean}
  /** Unique Id */
  id: string
  /** Name or title of navigation item */
  name: string
  /** Url associated with the item */
  href: string
}

export interface RequestContentNavigation {

}
