// This file is automatically generated based on the Looker Core API metadata.

export interface CreateDashboardRenderTask {
  /** Filter values to apply to the dashboard queries, in URL query format */
  dashboard_filters: string | null
  /** Dashboard layout style: single_column or tiled */
  dashboard_style: string | null
}

export interface RequestCreateDashboardRenderTask {
  /** Filter values to apply to the dashboard queries, in URL query format */
  dashboard_filters?: string | null
  /** Dashboard layout style: single_column or tiled */
  dashboard_style?: string | null
}
