// This file is automatically generated based on the Looker Core API metadata.

export enum CreateQueryTaskResultFormat {
  Json = 'json',
  JsonDetail = 'json_detail',
  JsonFe = 'json_fe',
  Csv = 'csv',
  Html = 'html',
  Md = 'md',
  Txt = 'txt',
  Xlsx = 'xlsx',
  Gsxml = 'gsxml'
}

export interface CreateQueryTask {
  /** Operations the current user is able to perform on this object */
  can: {[key: string]: boolean}
  /** Id of query to run */
  query_id: number | null
  /** Desired async query result format. Valid values are: "json", "json_detail", "json_fe", "csv", "html", "md", "txt", "xlsx", "gsxml". */
  result_format: CreateQueryTaskResultFormat | null
  /** Source of query task */
  source: string | null
  /** Create the task but defer execution */
  deferred: boolean
  /** Id of look associated with query. */
  look_id: number | null
  /** Id of dashboard associated with query. */
  dashboard_id: string | null
}

export interface RequestCreateQueryTask {
  /** Id of query to run */
  query_id?: number | null
  /** Desired async query result format. Valid values are: "json", "json_detail", "json_fe", "csv", "html", "md", "txt", "xlsx", "gsxml". */
  result_format?: CreateQueryTaskResultFormat | null
  /** Source of query task */
  source?: string | null
  /** Create the task but defer execution */
  deferred?: boolean
  /** Id of look associated with query. */
  look_id?: number | null
  /** Id of dashboard associated with query. */
  dashboard_id?: string | null
}
