// This file is automatically generated based on the Looker Core API metadata.

export interface CredentialsLDAP {
  /** Operations the current user is able to perform on this object */
  can: {[key: string]: boolean}
  /** Timestamp for the creation of this credential */
  created_at: string | null
  /** EMail address */
  email: string | null
  /** Has this credential been disabled? */
  is_disabled: boolean
  /** LDAP Distinguished name for this user (as-of the last login) */
  ldap_dn: string | null
  /** LDAP Unique ID for this user */
  ldap_id: string | null
  /** Timestamp for most recent login using credential */
  logged_in_at: string | null
  /** Short name for the type of this kind of credential */
  type: string | null
  /** Link to get this item */
  url: string | null
}

export interface RequestCredentialsLDAP {

}
