// This file is automatically generated based on the Looker Core API metadata.

export interface CredentialsApi {
  /** Operations the current user is able to perform on this object */
  can: {[key: string]: boolean}
  /** API key token */
  token: string | null
  /** Timestamp for the creation of this credential */
  created_at: string | null
  /** Has this credential been disabled? */
  is_disabled: boolean
  /** Short name for the type of this kind of credential */
  type: string | null
  /** Link to get this item */
  url: string | null
}

export interface RequestCredentialsApi {

}
