// This file is automatically generated based on the Looker Core API metadata.

export interface CredentialsApi3 {
  /** Operations the current user is able to perform on this object */
  can: {[key: string]: boolean}
  /** Unique Id */
  id: number
  /** API key client_id */
  client_id: string | null
  /** Timestamp for the creation of this credential */
  created_at: string | null
  /** Has this credential been disabled? */
  is_disabled: boolean
  /** Short name for the type of this kind of credential */
  type: string | null
  /** Link to get this item */
  url: string | null
}

export interface RequestCredentialsApi3 {

}
