// This file is automatically generated based on the Looker Core API metadata.

export interface CredentialsSaml {
  /** Operations the current user is able to perform on this object */
  can: {[key: string]: boolean}
  /** Timestamp for the creation of this credential */
  created_at: string | null
  /** EMail address */
  email: string | null
  /** Has this credential been disabled? */
  is_disabled: boolean
  /** Timestamp for most recent login using credential */
  logged_in_at: string | null
  /** Saml IdP's Unique ID for this user */
  saml_user_id: string | null
  /** Short name for the type of this kind of credential */
  type: string | null
  /** Link to get this item */
  url: string | null
}

export interface RequestCredentialsSaml {

}
