// This file is automatically generated based on the Looker Core API metadata.

export interface CredentialsLookerOpenid {
  /** Operations the current user is able to perform on this object */
  can: {[key: string]: boolean}
  /** Timestamp for the creation of this credential */
  created_at: string | null
  /** EMail address used for user login */
  email: string | null
  /** Has this credential been disabled? */
  is_disabled: boolean
  /** Timestamp for most recent login using credential */
  logged_in_at: string | null
  /** IP address of client for most recent login using credential */
  logged_in_ip: string | null
  /** Short name for the type of this kind of credential */
  type: string | null
  /** Link to get this item */
  url: string | null
  /** Link to get this user */
  user_url: string | null
}

export interface RequestCredentialsLookerOpenid {

}
