// This file is automatically generated based on the Looker Core API metadata.

export interface CredentialsEmail {
  /** Operations the current user is able to perform on this object */
  can: {[key: string]: boolean}
  /** Timestamp for the creation of this credential */
  created_at: string | null
  /** EMail address used for user login */
  email: string | null
  /** Force the user to change their password upon their next login */
  forced_password_reset_at_next_login: boolean
  /** Has this credential been disabled? */
  is_disabled: boolean
  /** Timestamp for most recent login using credential */
  logged_in_at: string | null
  /** Url with one-time use secret token that the user can use to reset password */
  password_reset_url: string | null
  /** Short name for the type of this kind of credential */
  type: string | null
  /** Link to get this item */
  url: string | null
  /** Link to get this user */
  user_url: string | null
}

export interface RequestCredentialsEmail {
  /** EMail address used for user login */
  email?: string | null
  /** Force the user to change their password upon their next login */
  forced_password_reset_at_next_login?: boolean
}
