// This file is automatically generated based on the Looker Core API metadata.

export interface CredentialsEmbed {
  /** Operations the current user is able to perform on this object */
  can: {[key: string]: boolean}
  /** Timestamp for the creation of this credential */
  created_at: string | null
  /** Embedder's id for a group to which this user was added during the most recent login */
  external_group_id: string | null
  /** Embedder's unique id for the user */
  external_user_id: string | null
  /** Unique Id */
  id: number
  /** Has this credential been disabled? */
  is_disabled: boolean
  /** Timestamp for most recent login using credential */
  logged_in_at: string | null
  /** Short name for the type of this kind of credential */
  type: string | null
  /** Link to get this item */
  url: string | null
}

export interface RequestCredentialsEmbed {

}
