// This file is automatically generated based on the Looker Core API metadata.

export interface DashboardLayoutComponent {
  /** Operations the current user is able to perform on this object */
  can: {[key: string]: boolean}
  /** Unique Id */
  id: string
  /** Id of Dashboard Layout */
  dashboard_layout_id: string | null
  /** Id Of Dashboard Element */
  dashboard_element_id: string | null
  /** Row */
  row: number | null
  /** Column */
  column: number | null
  /** Width */
  width: number | null
  /** Height */
  height: number | null
  /** Whether or not the dashboard layout component is deleted */
  deleted: boolean
  /** Dashboard element title, extracted from the Dashboard Element. */
  element_title: string | null
  /** Whether or not the dashboard element title is displayed. */
  element_title_hidden: boolean
  /** Visualization type, extracted from a query's vis_config */
  vis_type: string | null
}

export interface RequestDashboardLayoutComponent {
  /** Id of Dashboard Layout */
  dashboard_layout_id?: string | null
  /** Id Of Dashboard Element */
  dashboard_element_id?: string | null
  /** Row */
  row?: number | null
  /** Column */
  column?: number | null
  /** Width */
  width?: number | null
  /** Height */
  height?: number | null
}
