// This file is automatically generated based on the Looker Core API metadata.

export interface DashboardFilter {
  /** Operations the current user is able to perform on this object */
  can: {[key: string]: boolean}
  /** Unique Id */
  id: string
  /** Id of Dashboard */
  dashboard_id: string | null
  /** Name of filter */
  name: string | null
  /** Title of filter */
  title: string | null
  /** Type of filter: one of date, number, string, or field */
  type: string | null
  /** Default value of filter */
  default_value: string | null
  /** Model of filter (required if type = field) */
  model: string | null
  /** Explore of filter (required if type = field) */
  explore: string | null
  /** Dimension of filter (required if type = field) */
  dimension: string | null
  /** Field information */
  field: {[key: string]: any} | null
  /** Display order of this filter relative to other filters */
  row: number | null
  /** Array of listeners for faceted filters */
  listens_to_filters: string[] | null
  /** Whether the filter allows multiple filter values */
  allow_multiple_values: boolean
  /** Whether the filter requires a value to run the dashboard */
  required: boolean
  /** The visual configuration for this filter. Used to set up how the UI for this filter should appear. */
  ui_config: {[key: string]: any} | null
}

export interface RequestDashboardFilter {
  /** Name of filter */
  name?: string | null
  /** Title of filter */
  title?: string | null
  /** Type of filter: one of date, number, string, or field */
  type?: string | null
  /** Default value of filter */
  default_value?: string | null
  /** Model of filter (required if type = field) */
  model?: string | null
  /** Explore of filter (required if type = field) */
  explore?: string | null
  /** Dimension of filter (required if type = field) */
  dimension?: string | null
  /** Display order of this filter relative to other filters */
  row?: number | null
  /** Array of listeners for faceted filters */
  listens_to_filters?: string[] | null
  /** Whether the filter allows multiple filter values */
  allow_multiple_values?: boolean
  /** Whether the filter requires a value to run the dashboard */
  required?: boolean
  /** The visual configuration for this filter. Used to set up how the UI for this filter should appear. */
  ui_config?: {[key: string]: any} | null
}
