// This file is automatically generated based on the Looker Core API metadata.

export interface DashboardLookml {
  /** Id of Dashboard */
  dashboard_id: string | null
  /** lookml of UDD */
  lookml: string | null
}

export interface RequestDashboardLookml {

}
