// This file is automatically generated based on the Looker Core API metadata.

import { DashboardElement } from './dashboard_element'
import { DashboardFilter } from './dashboard_filter'
import { DashboardLayout } from './dashboard_layout'
import { DashboardSettings, RequestDashboardSettings } from './dashboard_settings'
import { FolderBase } from './folder_base'
import { LookModel } from './look_model'
import { SpaceBase } from './space_base'

export interface Dashboard {
  /** Operations the current user is able to perform on this object */
  can: {[key: string]: boolean}
  /** Content Favorite Id */
  content_favorite_id: number | null
  /** Id of content metadata */
  content_metadata_id: number | null
  /** Description */
  description: string | null
  /** Is Hidden */
  hidden: boolean
  /** Unique Id */
  id: string
  /** Model */
  model: LookModel | null
  /** Timezone in which the Dashboard will run by default. */
  query_timezone: string | null
  /** Is Read-only */
  readonly: boolean
  /** Refresh Interval, as a time duration phrase like "2 hours 30 minutes". A number with no time units will be interpreted as whole seconds. */
  refresh_interval: string | null
  /** Refresh Interval in milliseconds */
  refresh_interval_to_i: number | null
  /** Space */
  space: SpaceBase | null
  /** Folder */
  folder: FolderBase | null
  /** Dashboard Title */
  title: string | null
  /** Id of User */
  user_id: number | null
  /** Background color */
  background_color: string | null
  /** Time that the Dashboard was created. */
  created_at: string | null
  /** Elements */
  dashboard_elements: DashboardElement[] | null
  /** Filters */
  dashboard_filters: DashboardFilter[] | null
  /** Layouts */
  dashboard_layouts: DashboardLayout[] | null
  /** Whether or not a dashboard is 'soft' deleted. */
  deleted: boolean
  /** Time that the Dashboard was 'soft' deleted. */
  deleted_at: string | null
  /** Id of User that 'soft' deleted the dashboard. */
  deleter_id: number | null
  /** Relative path of URI of LookML file to edit the dashboard (LookML dashboard only). */
  edit_uri: string | null
  /** Number of times favorited */
  favorite_count: number | null
  /** Time the dashboard was last accessed */
  last_accessed_at: string | null
  /** Time last viewed in the Looker web UI */
  last_viewed_at: string | null
  /** configuration option that governs how dashboard loading will happen. */
  load_configuration: string | null
  /** Links this dashboard to a particular LookML dashboard such that calling a **sync** operation on that LookML dashboard will update this dashboard to match. */
  lookml_link_id: string | null
  /** Show filters bar.  **Security Note:** This property only affects the *cosmetic* appearance of the dashboard, not a user's ability to access data. Hiding the filters bar does **NOT** prevent users from changing filters by other means. For information on how to set up secure data access control policies, see [Control User Access to Data](https://looker.com/docs/r/api/control-access) */
  show_filters_bar: boolean
  /** Show title */
  show_title: boolean
  /** Content Metadata Slug */
  slug: string | null
  /** Id of Space */
  space_id: string | null
  /** Id of folder */
  folder_id: string | null
  /** Color of text on text tiles */
  text_tile_text_color: string | null
  /** Tile background color */
  tile_background_color: string | null
  /** Tile text color */
  tile_text_color: string | null
  /** Title color */
  title_color: string | null
  /** Number of times viewed in the Looker web UI */
  view_count: number | null
  /** Dashboard visual settings only applicable to dashboards-next (beta) */
  settings: DashboardSettings | null
  /** The preferred route for viewing this dashboard (ie: dashboards or dashboards-next) */
  preferred_viewer: string | null
}

export interface RequestDashboard {
  /** Description */
  description?: string | null
  /** Is Hidden */
  hidden?: boolean
  /** Timezone in which the Dashboard will run by default. */
  query_timezone?: string | null
  /** Refresh Interval, as a time duration phrase like "2 hours 30 minutes". A number with no time units will be interpreted as whole seconds. */
  refresh_interval?: string | null
  /** Dashboard Title */
  title?: string | null
  /** Background color */
  background_color?: string | null
  /** Whether or not a dashboard is 'soft' deleted. */
  deleted?: boolean
  /** configuration option that governs how dashboard loading will happen. */
  load_configuration?: string | null
  /** Links this dashboard to a particular LookML dashboard such that calling a **sync** operation on that LookML dashboard will update this dashboard to match. */
  lookml_link_id?: string | null
  /** Show filters bar.  **Security Note:** This property only affects the *cosmetic* appearance of the dashboard, not a user's ability to access data. Hiding the filters bar does **NOT** prevent users from changing filters by other means. For information on how to set up secure data access control policies, see [Control User Access to Data](https://looker.com/docs/r/api/control-access) */
  show_filters_bar?: boolean
  /** Show title */
  show_title?: boolean
  /** Content Metadata Slug */
  slug?: string | null
  /** Id of Space */
  space_id?: string | null
  /** Id of folder */
  folder_id?: string | null
  /** Color of text on text tiles */
  text_tile_text_color?: string | null
  /** Tile background color */
  tile_background_color?: string | null
  /** Tile text color */
  tile_text_color?: string | null
  /** Title color */
  title_color?: string | null
  /** Dashboard visual settings only applicable to dashboards-next (beta) */
  settings?: RequestDashboardSettings | null
  /** The preferred route for viewing this dashboard (ie: dashboards or dashboards-next) */
  preferred_viewer?: string | null
}
