// This file is automatically generated based on the Looker Core API metadata.

import { DashboardLayoutComponent } from './dashboard_layout_component'

export interface DashboardLayout {
  /** Operations the current user is able to perform on this object */
  can: {[key: string]: boolean}
  /** Unique Id */
  id: string
  /** Id of Dashboard */
  dashboard_id: string | null
  /** Type */
  type: string | null
  /** Is Active */
  active: boolean
  /** Column Width */
  column_width: number | null
  /** Width */
  width: number | null
  /** Whether or not the dashboard layout is deleted. */
  deleted: boolean
  /** Title extracted from the dashboard this layout represents. */
  dashboard_title: string | null
  /** Components */
  dashboard_layout_components: DashboardLayoutComponent[] | null
}

export interface RequestDashboardLayout {
  /** Id of Dashboard */
  dashboard_id?: string | null
  /** Type */
  type?: string | null
  /** Is Active */
  active?: boolean
  /** Column Width */
  column_width?: number | null
  /** Width */
  width?: number | null
}
