// This file is automatically generated based on the Looker Core API metadata.

export interface DashboardSettings {
  /** Page margin (side) width */
  page_side_margins: number | null
  /** Background color for the dashboard */
  page_background_color: string | null
  /** Title alignment on dashboard tiles */
  tile_title_alignment: string | null
  /** Space between tiles */
  tile_space_between: number | null
  /** Background color for tiles */
  tile_background_color: string | null
  /** Tile shadow on/off */
  tile_shadow: boolean
  /** Key color */
  key_color: string | null
}

export interface RequestDashboardSettings {
  /** Page margin (side) width */
  page_side_margins?: number | null
  /** Background color for the dashboard */
  page_background_color?: string | null
  /** Title alignment on dashboard tiles */
  tile_title_alignment?: string | null
  /** Space between tiles */
  tile_space_between?: number | null
  /** Background color for tiles */
  tile_background_color?: string | null
  /** Tile shadow on/off */
  tile_shadow?: boolean
  /** Key color */
  key_color?: string | null
}
