// This file is automatically generated based on the Looker Core API metadata.

import { FolderBase } from './folder_base'
import { LookModel } from './look_model'
import { SpaceBase } from './space_base'

export interface DashboardBase {
  /** Operations the current user is able to perform on this object */
  can: {[key: string]: boolean}
  /** Content Favorite Id */
  content_favorite_id: number | null
  /** Id of content metadata */
  content_metadata_id: number | null
  /** Description */
  description: string | null
  /** Is Hidden */
  hidden: boolean
  /** Unique Id */
  id: string
  /** Model */
  model: LookModel | null
  /** Timezone in which the Dashboard will run by default. */
  query_timezone: string | null
  /** Is Read-only */
  readonly: boolean
  /** Refresh Interval, as a time duration phrase like "2 hours 30 minutes". A number with no time units will be interpreted as whole seconds. */
  refresh_interval: string | null
  /** Refresh Interval in milliseconds */
  refresh_interval_to_i: number | null
  /** Space */
  space: SpaceBase | null
  /** Folder */
  folder: FolderBase | null
  /** Dashboard Title */
  title: string | null
  /** Id of User */
  user_id: number | null
}

export interface RequestDashboardBase {

}
