// This file is automatically generated based on the Looker Core API metadata.

import { DataActionFormSelectOption } from './data_action_form_select_option'

export interface DataActionFormField {
  /** Name */
  name: string | null
  /** Human-readable label */
  label: string | null
  /** Description of field */
  description: string | null
  /** Type of field. */
  type: string | null
  /** Default value of the field. */
  default: string | null
  /** The URL for an oauth link, if type is 'oauth_link'. */
  oauth_url: string | null
  /** Whether or not a field supports interactive forms. */
  interactive: boolean
  /** Whether or not the field is required. This is a user-interface hint. A user interface displaying this form should not submit it without a value for this field. The action server must also perform this validation. */
  required: boolean
  /** If the form type is 'select', a list of options to be selected from. */
  options: DataActionFormSelectOption[] | null
}

export interface RequestDataActionFormField {

}
