// This file is automatically generated based on the Looker Core API metadata.

import { ValidationError } from './validation_error'

export interface DataActionResponse {
  /** ID of the webhook event that sent this data action. In some error conditions, this may be null. */
  webhook_id: string | null
  /** Whether the data action was successful. */
  success: boolean
  /** When true, indicates that the client should refresh (rerun) the source query because the data may have been changed by the action. */
  refresh_query: boolean
  /** Validation errors returned by the data action server. */
  validation_errors: ValidationError | null
  /** Optional message returned by the data action server describing the state of the action that took place. This can be used to implement custom failure messages. If a failure is related to a particular form field, the server should send back a validation error instead. The Looker web UI does not currently display any message if the action indicates 'success', but may do so in the future. */
  message: string | null
}

export interface RequestDataActionResponse {

}
