// This file is automatically generated based on the Looker Core API metadata.

export interface DataActionRequest {
  /** The JSON describing the data action. This JSON should be considered opaque and should be passed through unmodified from the query result it came from. */
  action: {[key: string]: string} | null
  /** User input for any form values the data action might use. */
  form_values: {[key: string]: string} | null
}

export interface RequestDataActionRequest {
  /** The JSON describing the data action. This JSON should be considered opaque and should be passed through unmodified from the query result it came from. */
  action?: {[key: string]: string} | null
  /** User input for any form values the data action might use. */
  form_values?: {[key: string]: string} | null
}
