// This file is automatically generated based on the Looker Core API metadata.

import { DataActionFormField } from './data_action_form_field'
import { DataActionUserState } from './data_action_user_state'

export interface DataActionForm {
  /** User state */
  state: DataActionUserState | null
  /** Array of form fields. */
  fields: DataActionFormField[] | null
}

export interface RequestDataActionForm {

}
