// This file is automatically generated based on the Looker Core API metadata.

export interface DataActionFormSelectOption {
  /** Name */
  name: string | null
  /** Human-readable label */
  label: string | null
}

export interface RequestDataActionFormSelectOption {

}
