// This file is automatically generated based on the Looker Core API metadata.

export interface DataActionUserState {
  /** User state data */
  data: string | null
  /** Time in seconds until the state needs to be refreshed */
  refresh_time: number | null
}

export interface RequestDataActionUserState {

}
