// This file is automatically generated based on the Looker Core API metadata.

export interface DatafluxSlug {
  /** Operations the current user is able to perform on this object */
  can: {[key: string]: boolean}
  /** Unique Id */
  id: number
  /** GUID used to identify slug */
  guid: string | null
  /** ID of associated query */
  query_id: number | null
  /** Time that the slug was last fetched */
  last_fetched: string | null
  /** Time that the slug was created */
  created_at: string | null
}

export interface RequestDatafluxSlug {
  /** GUID used to identify slug */
  guid?: string | null
  /** ID of associated query */
  query_id?: number | null
}
