// This file is automatically generated based on the Looker Core API metadata.

import { DBConnectionOverride, RequestDBConnectionOverride } from './db_connection_override'
import { Dialect } from './dialect'
import { Snippet } from './snippet'

export interface DBConnection {
  /** Operations the current user is able to perform on this object */
  can: {[key: string]: boolean}
  /** Name of the connection. Also used as the unique identifier */
  name: string
  /** (Read-only) SQL Dialect details */
  dialect: Dialect
  /** SQL Runner snippets for this connection */
  snippets: Snippet[]
  /** Host name/address of server */
  host: string | null
  /** Port number on server */
  port: string | null
  /** Username for server authentication */
  username: string | null
  /** Whether the connection uses OAuth for authentication. */
  uses_oauth: boolean
  /** Database name */
  database: string | null
  /** Time zone of database */
  db_timezone: string | null
  /** Timezone to use in queries */
  query_timezone: string | null
  /** Scheme name */
  schema: string | null
  /** Maximum number of concurrent connection to use */
  max_connections: number | null
  /** Maximum size of query in GBs (BigQuery only, can be a user_attribute name) */
  max_billing_gigabytes: string | null
  /** Use SSL/TLS when connecting to server */
  ssl: boolean
  /** Verify the SSL */
  verify_ssl: boolean
  /** Name of temporary database (if used) */
  tmp_db_name: string | null
  /** Additional params to add to JDBC connection string */
  jdbc_additional_params: string | null
  /** Connection Pool Timeout, in seconds */
  pool_timeout: number | null
  /** (Read/Write) SQL Dialect name */
  dialect_name: string | null
  /** Creation date for this connection */
  created_at: string | null
  /** Id of user who last modified this connection configuration */
  user_id: string | null
  /** Is this an example connection? */
  example: boolean
  /** (Limited access feature) Are per user db credentials enabled. Enabling will remove previously set username and password */
  user_db_credentials: boolean | null
  /** Fields whose values map to user attribute names */
  user_attribute_fields: string[] | null
  /** Cron string specifying when maintenance such as PDT trigger checks and drops should be performed */
  maintenance_cron: string | null
  /** Unix timestamp at start of last completed PDT trigger check process */
  last_regen_at: string | null
  /** Unix timestamp at start of last completed PDT reap process */
  last_reap_at: string | null
  /** Precache tables in the SQL Runner */
  sql_runner_precache_tables: boolean
  /** SQL statements (semicolon separated) to issue after connecting to the database. Requires `custom_after_connect_statements` license feature */
  after_connect_statements: string | null
  /** db_connection_override for this connection in the `pdt` maintenance context */
  pdt_context_override: DBConnectionOverride | null
  /** Is this connection created and managed by Looker */
  managed: boolean
}

export interface RequestDBConnection {
  /** Name of the connection. Also used as the unique identifier */
  name?: string
  /** Host name/address of server */
  host?: string | null
  /** Port number on server */
  port?: string | null
  /** Username for server authentication */
  username?: string | null
  /** (Write-Only) Password for server authentication */
  password?: string | null
  /** (Write-Only) Base64 encoded Certificate body for server authentication (when appropriate for dialect). */
  certificate?: string | null
  /** (Write-Only) Certificate keyfile type - .json or .p12 */
  file_type?: string | null
  /** Database name */
  database?: string | null
  /** Time zone of database */
  db_timezone?: string | null
  /** Timezone to use in queries */
  query_timezone?: string | null
  /** Scheme name */
  schema?: string | null
  /** Maximum number of concurrent connection to use */
  max_connections?: number | null
  /** Maximum size of query in GBs (BigQuery only, can be a user_attribute name) */
  max_billing_gigabytes?: string | null
  /** Use SSL/TLS when connecting to server */
  ssl?: boolean
  /** Verify the SSL */
  verify_ssl?: boolean
  /** Name of temporary database (if used) */
  tmp_db_name?: string | null
  /** Additional params to add to JDBC connection string */
  jdbc_additional_params?: string | null
  /** Connection Pool Timeout, in seconds */
  pool_timeout?: number | null
  /** (Read/Write) SQL Dialect name */
  dialect_name?: string | null
  /** (Limited access feature) Are per user db credentials enabled. Enabling will remove previously set username and password */
  user_db_credentials?: boolean | null
  /** Fields whose values map to user attribute names */
  user_attribute_fields?: string[] | null
  /** Cron string specifying when maintenance such as PDT trigger checks and drops should be performed */
  maintenance_cron?: string | null
  /** Precache tables in the SQL Runner */
  sql_runner_precache_tables?: boolean
  /** SQL statements (semicolon separated) to issue after connecting to the database. Requires `custom_after_connect_statements` license feature */
  after_connect_statements?: string | null
  /** db_connection_override for this connection in the `pdt` maintenance context */
  pdt_context_override?: RequestDBConnectionOverride | null
}
