// This file is automatically generated based on the Looker Core API metadata.

export interface Dialect {
  /** The name of the dialect */
  name: string
  /** The human-readable label of the connection */
  label: string
  /** Whether the dialect supports query cost estimates */
  supports_cost_estimate: boolean
  /** PDT index columns */
  persistent_table_indexes: string
  /** PDT sortkey columns */
  persistent_table_sortkeys: string
  /** PDT distkey column */
  persistent_table_distkey: string
  /** Suports streaming results */
  supports_streaming: boolean
  /** Should SQL Runner snippets automatically be run */
  automatically_run_sql_runner_snippets: boolean
  /** Array of names of the tests that can be run on a connection using this dialect */
  connection_tests: string[]
  /** Is supported with the inducer (i.e. generate from sql) */
  supports_inducer: boolean
  /** Can multiple databases be accessed from a connection using this dialect */
  supports_multiple_databases: boolean
  /** Whether the dialect supports allowing Looker to build persistent derived tables */
  supports_persistent_derived_tables: boolean
  /** Does the database have client SSL support settable through the JDBC string explicitly? */
  has_ssl_support: boolean
}

export interface RequestDialect {

}
