// This file is automatically generated based on the Looker Core API metadata.

import { DialectInfoOptions } from './dialect_info_options'

export interface DialectInfo {
  /** Operations the current user is able to perform on this object */
  can: {[key: string]: boolean}
  /** Default number max connections */
  default_max_connections: string | null
  /** Default port number */
  default_port: string | null
  /** Is the supporting driver installed */
  installed: boolean
  /** The human-readable label of the connection */
  label: string | null
  /** What the dialect calls the equivalent of a normal SQL table */
  label_for_database_equivalent: string | null
  /** The name of the dialect */
  name: string | null
  /** Option support details */
  supported_options: DialectInfoOptions | null
}

export interface RequestDialectInfo {

}
