// This file is automatically generated based on the Looker Core API metadata.

export interface DisableAlertRequest {
  /** Disable Reason */
  reason: string
}

export interface RequestDisableAlertRequest {
  /** Disable Reason */
  reason?: string
}
