// This file is automatically generated based on the Looker Core API metadata.

export interface DiscretePalette {
  /** Unique identity string */
  id: string
  /** Label for palette */
  label: string | null
  /** Type of palette */
  type: string
  /** Array of colors in the palette */
  colors: string[]
}

export interface RequestDiscretePalette {
  /** Label for palette */
  label?: string | null
  /** Type of palette */
  type?: string
  /** Array of colors in the palette */
  colors?: string[]
}
