// This file is automatically generated based on the Looker Core API metadata.

export interface EmbedSsoUrl {
  /** The signed embed URL. Any modification to this string will invalidate the signature and make the URL unusable. */
  url: string | null
}

export interface RequestEmbedSsoUrl {

}
