// This file is automatically generated based on the Looker Core API metadata.

export interface APIError {
  /** Error details */
  message: string | null
  /** Documentation link */
  documentation_url: string | null
}

export interface RequestError {

}
