// This file is automatically generated based on the Looker Core API metadata.

import { DashboardElement } from './dashboard_element'
import { DashboardFilter } from './dashboard_filter'
import { Look } from './look'

export interface FindAndReplaceResponse {
  /**  */
  looks: Look[] | null
  /**  */
  dashboard_elements: DashboardElement[] | null
  /**  */
  dashboard_filters: DashboardFilter[] | null
}

export interface RequestFindAndReplaceResponse {

}
