// This file is automatically generated based on the Looker Core API metadata.

export interface FolderBase {
  /** Unique Name */
  name: string
  /** Id of Parent. If the parent id is null, this is a root-level entry */
  parent_id: string | null
  /** Unique Id */
  id: string
  /** Id of content metadata */
  content_metadata_id: number | null
  /** Time the folder was created */
  created_at: string | null
  /** User Id of Creator */
  creator_id: number | null
  /** Children Count */
  child_count: number | null
  /** Embedder's Id if this folder was autogenerated as an embedding shared folder via 'external_group_id' in an SSO embed login */
  external_id: string | null
  /** Folder is an embed folder */
  is_embed: boolean
  /** Folder is the root embed shared folder */
  is_embed_shared_root: boolean
  /** Folder is the root embed users folder */
  is_embed_users_root: boolean
  /** Folder is a user's personal folder */
  is_personal: boolean
  /** Folder is descendant of a user's personal folder */
  is_personal_descendant: boolean
  /** Folder is the root shared folder */
  is_shared_root: boolean
  /** Folder is the root user folder */
  is_users_root: boolean
  /** Operations the current user is able to perform on this object */
  can: {[key: string]: boolean}
}

export interface RequestFolderBase {
  /** Unique Name */
  name?: string
  /** Id of Parent. If the parent id is null, this is a root-level entry */
  parent_id?: string | null
}
