// This file is automatically generated based on the Looker Core API metadata.

export interface GitConnectionTest {
  /** Operations the current user is able to perform on this object */
  can: {[key: string]: boolean}
  /** Human readable string describing the test */
  description: string | null
  /** A short string, uniquely naming this test */
  id: string
}

export interface RequestGitConnectionTest {

}
