// This file is automatically generated based on the Looker Core API metadata.

export interface GroupIdForGroupInclusion {
  /** Id of group */
  group_id: number | null
}

export interface RequestGroupIdForGroupInclusion {

}
