// This file is automatically generated based on the Looker Core API metadata.

export interface Group {
  /** Operations the current user is able to perform on this object */
  can: {[key: string]: boolean}
  /** Group can be used in content access controls */
  can_add_to_content_metadata: boolean
  /** Currently logged in user is group member */
  contains_current_user: boolean
  /** External Id group if embed group */
  external_group_id: string | null
  /** Group membership controlled outside of Looker */
  externally_managed: boolean
  /** Unique Id */
  id: number
  /** New users are added to this group by default */
  include_by_default: boolean
  /** Name of group */
  name: string | null
  /** Number of users included in this group */
  user_count: number | null
}

export interface RequestGroup {
  /** Group can be used in content access controls */
  can_add_to_content_metadata?: boolean
  /** Name of group */
  name?: string | null
}
