// This file is automatically generated based on the Looker Core API metadata.

export interface GroupIdForGroupUserInclusion {
  /** Id of user */
  user_id: number | null
}

export interface RequestGroupIdForGroupUserInclusion {

}
