// This file is automatically generated based on the Looker Core API metadata.

import { HomepageItem } from './homepage_item'

export interface HomepageSection {
  /** Operations the current user is able to perform on this object */
  can: {[key: string]: boolean}
  /** Time at which this section was created. */
  created_at: string | null
  /** Time at which this section was deleted. */
  deleted_at: string | null
  /** A URL pointing to a page showing further information about the content in the section. */
  detail_url: string | null
  /** Id reference to parent homepage */
  homepage_id: number | null
  /** Items in the homepage section */
  homepage_items: HomepageItem[] | null
  /** Unique Id */
  id: string
  /** Is this a header section (has no items) */
  is_header: boolean
  /** ids of the homepage items in the order they should be displayed */
  item_order: number[] | null
  /** Name of row */
  title: string | null
  /** Time at which this section was last updated. */
  updated_at: string | null
  /** Description of the content found in this section. */
  description: string | null
}

export interface RequestHomepageSection {
  /** Time at which this section was deleted. */
  deleted_at?: string | null
  /** Id reference to parent homepage */
  homepage_id?: number | null
  /** ids of the homepage items in the order they should be displayed */
  item_order?: number[] | null
  /** Name of row */
  title?: string | null
  /** Description of the content found in this section. */
  description?: string | null
}
