// This file is automatically generated based on the Looker Core API metadata.

export interface ImportedProject {
  /** Dependency name */
  name: string | null
  /** Url for a remote dependency */
  url: string | null
  /** Ref for a remote dependency */
  ref: string | null
  /** Flag signifying if a dependency is remote or local */
  is_remote: boolean
  /** Operations the current user is able to perform on this object */
  can: {[key: string]: boolean}
}

export interface RequestImportedProject {

}
