// This file is automatically generated based on the Looker Core API metadata.

export interface InternalHelpResources {
  /** Operations the current user is able to perform on this object */
  can: {[key: string]: boolean}
  /** If true and internal help resources content is not blank then the link for internal help resources will be shown in the help menu and the content displayed within Looker */
  enabled: boolean
}

export interface RequestInternalHelpResources {
  /** If true and internal help resources content is not blank then the link for internal help resources will be shown in the help menu and the content displayed within Looker */
  enabled?: boolean
}
