// This file is automatically generated based on the Looker Core API metadata.

export interface IntegrationProxyAccountIdentity {
  /** Operations the current user is able to perform on this object */
  can: {[key: string]: boolean}
  /** The id of the federated user */
  user_id: string
  /** The name of the federated user */
  username: string | null
  /** The id of the installed scope, for slack this would be team_id */
  install_scope_id: string
  /** The display name of the installed scope, for slack this would be team name */
  install_scope_display_name: string | null
}

export interface RequestIntegrationProxyAccountIdentity {

}
