// This file is automatically generated based on the Looker Core API metadata.

export interface InternalHelpResourcesContent {
  /** Operations the current user is able to perform on this object */
  can: {[key: string]: boolean}
  /** Text to display in the help menu item which will display the internal help resources */
  organization_name: string | null
  /** Content to be displayed in the internal help resources page/modal */
  markdown_content: string | null
}

export interface RequestInternalHelpResourcesContent {
  /** Text to display in the help menu item which will display the internal help resources */
  organization_name?: string | null
  /** Content to be displayed in the internal help resources page/modal */
  markdown_content?: string | null
}
