// This file is automatically generated based on the Looker Core API metadata.

export interface JsonEntity {
  /** Operations the current user is able to perform on this object */
  can: {[key: string]: boolean}
}

export interface RequestJsonEntity {

}
