// This file is automatically generated based on the Looker Core API metadata.

import { UserAttribute } from './user_attribute'

export interface LDAPUserAttributeRead {
  /** Name of User Attribute in LDAP */
  name: string | null
  /** Required to be in LDAP assertion for login to be allowed to succeed */
  required: boolean
  /** Looker User Attributes */
  user_attributes: UserAttribute[] | null
  /** Link to ldap config */
  url: string | null
}

export interface RequestLDAPUserAttributeRead {

}
