// This file is automatically generated based on the Looker Core API metadata.

export interface LDAPGroupWrite {
  /** Name of group in LDAP */
  name: string | null
  /** Looker Role Ids */
  role_ids: number[] | null
  /** Link to ldap config */
  url: string | null
}

export interface RequestLDAPGroupWrite {
  /** Name of group in LDAP */
  name?: string | null
  /** Looker Role Ids */
  role_ids?: number[] | null
}
