// This file is automatically generated based on the Looker Core API metadata.

export interface LDAPUserAttributeWrite {
  /** Name of User Attribute in LDAP */
  name: string | null
  /** Required to be in LDAP assertion for login to be allowed to succeed */
  required: boolean
  /** Looker User Attribute Ids */
  user_attribute_ids: number[] | null
  /** Link to ldap config */
  url: string | null
}

export interface RequestLDAPUserAttributeWrite {
  /** Name of User Attribute in LDAP */
  name?: string | null
  /** Required to be in LDAP assertion for login to be allowed to succeed */
  required?: boolean
  /** Looker User Attribute Ids */
  user_attribute_ids?: number[] | null
}
