// This file is automatically generated based on the Looker Core API metadata.

import { Role } from './role'

export interface LDAPGroupRead {
  /** Name of group in LDAP */
  name: string | null
  /** Looker Roles */
  roles: Role[] | null
  /** Link to ldap config */
  url: string | null
}

export interface RequestLDAPGroupRead {

}
