// This file is automatically generated based on the Looker Core API metadata.

export interface LDAPUser {
  /** Array of user's email addresses and aliases for use in migration */
  all_emails: string[] | null
  /** Dictionary of user's attributes (name/value) */
  attributes: {[key: string]: string} | null
  /** Primary email address */
  email: string | null
  /** First name */
  first_name: string | null
  /** Array of user's groups (group names only) */
  groups: string[] | null
  /** Last Name */
  last_name: string | null
  /** LDAP's distinguished name for the user record */
  ldap_dn: string | null
  /** LDAP's Unique ID for the user */
  ldap_id: string | null
  /** Array of user's roles (role names only) */
  roles: string[] | null
  /** Operations the current user is able to perform on this object */
  can: {[key: string]: boolean}
  /** Link to ldap config */
  url: string | null
}

export interface RequestLDAPUser {

}
