// This file is automatically generated based on the Looker Core API metadata.

export interface LegacyFeature {
  /** Operations the current user is able to perform on this object */
  can: {[key: string]: boolean}
  /** Unique Id */
  id: string
  /** Name */
  name: string | null
  /** Description */
  description: string | null
  /** Whether this feature has been enabled by a user */
  enabled_locally: boolean
  /** Whether this feature is currently enabled */
  enabled: boolean
  /** Looker version where this feature became a legacy feature */
  disallowed_as_of_version: string | null
  /** Looker version where this feature will be automatically disabled */
  disable_on_upgrade_to_version: string | null
  /** Future Looker version where this feature will be removed */
  end_of_life_version: string | null
  /** URL for documentation about this feature */
  documentation_url: string | null
  /** Approximate date that this feature will be automatically disabled. */
  approximate_disable_date: string | null
  /** Approximate date that this feature will be removed. */
  approximate_end_of_life_date: string | null
  /** Whether this legacy feature may have been automatically disabled when upgrading to the current version. */
  has_disabled_on_upgrade: boolean
}

export interface RequestLegacyFeature {
  /** Whether this feature has been enabled by a user */
  enabled_locally?: boolean
}
