// This file is automatically generated based on the Looker Core API metadata.

export interface Locale {
  /** Code for Locale */
  code: string | null
  /** Name of Locale in its own language */
  native_name: string | null
  /** Name of Locale in English */
  english_name: string | null
}

export interface RequestLocale {

}
