// This file is automatically generated based on the Looker Core API metadata.

export interface LocalizationSettings {
  /** Default locale for localization */
  default_locale: string | null
  /** Localization level - strict or permissive */
  localization_level: string | null
  /** Operations the current user is able to perform on this object */
  can: {[key: string]: boolean}
}

export interface RequestLocalizationSettings {

}
