// This file is automatically generated based on the Looker Core API metadata.

export interface LookmlModelNavExplore {
  /** Name of the explore */
  name: string | null
  /** Description for the explore */
  description: string
  /** Label for the explore */
  label: string | null
  /** Is this explore marked as hidden */
  hidden: boolean
  /** Label used to group explores in the navigation menus */
  group_label: string | null
  /** Operations the current user is able to perform on this object */
  can: {[key: string]: boolean}
}

export interface RequestLookmlModelNavExplore {

}
