// This file is automatically generated based on the Looker Core API metadata.

export interface LookmlModelExploreAccessFilter {
  /** Field to be filtered */
  field: string | null
  /** User attribute name */
  user_attribute: string | null
}

export interface RequestLookmlModelExploreAccessFilter {

}
