// This file is automatically generated based on the Looker Core API metadata.

export interface LookmlModelExploreSupportedMeasureType {
  dimension_type: string | null
  measure_types: string[] | null
}

export interface RequestLookmlModelExploreSupportedMeasureType {

}
