// This file is automatically generated based on the Looker Core API metadata.

import { LookBasic } from './look_basic'

export interface LookMovePlan {
  looks_to_copy: LookBasic[] | null
  looks_to_move: LookBasic[] | null
}

export interface RequestLookMovePlan {

}
