// This file is automatically generated based on the Looker Core API metadata.

export interface LookmlModelExploreSet {
  /** Name */
  name: string | null
  /** Value set */
  value: string[] | null
}

export interface RequestLookmlModelExploreSet {

}
