// This file is automatically generated based on the Looker Core API metadata.

export interface LookmlTest {
  /** Operations the current user is able to perform on this object */
  can: {[key: string]: boolean}
  /** Name of model containing this test. */
  model_name: string
  /** Name of this test. */
  name: string
  /** Name of the explore this test runs a query against */
  explore_name: string
  /** The url parameters that can be used to reproduce this test's query on an explore. */
  query_url_params: string
  /** Name of the LookML file containing this test. */
  file: string
  /** Line number of this test in LookML. */
  line: number | null
}

export interface RequestLookmlTest {

}
