// This file is automatically generated based on the Looker Core API metadata.

import { FolderBase } from './folder_base'
import { LookModel } from './look_model'
import { SpaceBase } from './space_base'

export interface Look {
  /** Operations the current user is able to perform on this object */
  can: {[key: string]: boolean}
  /** Id of content metadata */
  content_metadata_id: number | null
  /** Unique Id */
  id: number
  /** Look Title */
  title: string | null
  /** Content Favorite Id */
  content_favorite_id: number | null
  /** Time that the Look was created. */
  created_at: string | null
  /** Whether or not a look is 'soft' deleted. */
  deleted: boolean
  /** Time that the Look was deleted. */
  deleted_at: string | null
  /** Id of User that deleted the look. */
  deleter_id: number | null
  /** Description */
  description: string | null
  /** Embed Url */
  embed_url: string | null
  /** Excel File Url */
  excel_file_url: string | null
  /** Number of times favorited */
  favorite_count: number | null
  /** Google Spreadsheet Formula */
  google_spreadsheet_formula: string | null
  /** Image Embed Url */
  image_embed_url: string | null
  /** auto-run query when Look viewed */
  is_run_on_load: boolean
  /** Time that the Look was last accessed by any user */
  last_accessed_at: string | null
  /** Id of User that last updated the look. */
  last_updater_id: number | null
  /** Time last viewed in the Looker web UI */
  last_viewed_at: string | null
  /** Model */
  model: LookModel | null
  /** Is Public */
  public: boolean | null
  /** Public Slug */
  public_slug: string | null
  /** Public Url */
  public_url: string | null
  /** Query Id */
  query_id: number | null
  /** Short Url */
  short_url: string | null
  /** Space of this Look */
  space: SpaceBase | null
  /** Folder of this Look */
  folder: FolderBase | null
  /** Space Id */
  space_id: string | null
  /** Folder Id */
  folder_id: string | null
  /** Time that the Look was updated. */
  updated_at: string | null
  /** User Id */
  user_id: number | null
  /** Number of times viewed in the Looker web UI */
  view_count: number | null
}

export interface RequestLook {
  /** Look Title */
  title?: string | null
  /** Whether or not a look is 'soft' deleted. */
  deleted?: boolean
  /** Description */
  description?: string | null
  /** auto-run query when Look viewed */
  is_run_on_load?: boolean
  /** Is Public */
  public?: boolean | null
  /** Query Id */
  query_id?: number | null
  /** Space Id */
  space_id?: string | null
  /** Folder Id */
  folder_id?: string | null
  /** User Id */
  user_id?: number | null
}
