// This file is automatically generated based on the Looker Core API metadata.

import { LookmlModelNavExplore } from './lookml_model_nav_explore'

export interface LookmlModel {
  /** Operations the current user is able to perform on this object */
  can: {[key: string]: boolean}
  /** Array of names of connections this model is allowed to use */
  allowed_db_connection_names: string[] | null
  /** Array of explores (if has_content) */
  explores: LookmlModelNavExplore[] | null
  /** Does this model declaration have have lookml content? */
  has_content: boolean
  /** UI-friendly name for this model */
  label: string | null
  /** Name of the model. Also used as the unique identifier */
  name: string | null
  /** Name of project containing the model */
  project_name: string | null
  /** Is this model allowed to use all current and future connections */
  unlimited_db_connections: boolean
}

export interface RequestLookmlModel {
  /** Array of names of connections this model is allowed to use */
  allowed_db_connection_names?: string[] | null
  /** Name of the model. Also used as the unique identifier */
  name?: string | null
  /** Name of project containing the model */
  project_name?: string | null
  /** Is this model allowed to use all current and future connections */
  unlimited_db_connections?: boolean
}
