// This file is automatically generated based on the Looker Core API metadata.

export interface LookmlModelExploreAlwaysFilter {
  /** Name */
  name: string | null
  /** Value */
  value: string | null
}

export interface RequestLookmlModelExploreAlwaysFilter {

}
