// This file is automatically generated based on the Looker Core API metadata.

export interface LookmlModelExploreError {
  /** Error Message */
  message: string | null
  /** Details */
  details: any | null
  /** Error source location */
  error_pos: string | null
  /** Is this a field error */
  field_error: boolean
}

export interface RequestLookmlModelExploreError {

}
