// This file is automatically generated based on the Looker Core API metadata.

export interface LookBasic {
  /** Operations the current user is able to perform on this object */
  can: {[key: string]: boolean}
  /** Id of content metadata */
  content_metadata_id: number | null
  /** Unique Id */
  id: number
  /** Look Title */
  title: string | null
}

export interface RequestLookBasic {

}
