// This file is automatically generated based on the Looker Core API metadata.

export interface LookModel {
  /** Model Id */
  id: string
  /** Model Label */
  label: string | null
}

export interface RequestLookModel {

}
