// This file is automatically generated based on the Looker Core API metadata.

export interface LookmlModelExploreJoins {
  /** Name of this join (and name of the view to join) */
  name: string | null
  /** Fields referenced by the join */
  dependent_fields: string[] | null
  /** Fields of the joined view to pull into this explore */
  fields: string[]
  /** Name of the dimension in this explore whose value is in the primary key of the joined view */
  foreign_key: string
  /** Name of view to join */
  from: string
  /** Specifies whether all queries must use an outer join */
  outer_only: boolean | null
  /** many_to_one, one_to_one, one_to_many, many_to_many */
  relationship: string | null
  /** Names of joins that must always be included in SQL queries */
  required_joins: string[]
  /** SQL expression that produces a foreign key */
  sql_foreign_key: string
  /** SQL ON expression describing the join condition */
  sql_on: string
  /** SQL table name to join */
  sql_table_name: string
  /** The join type: left_outer, full_outer, inner, or cross */
  type: string
  /** Label to display in UI selectors */
  view_label: string
}

export interface RequestLookmlModelExploreJoins {

}
