// This file is automatically generated based on the Looker Core API metadata.

export interface MarketplaceInstallationEntitlement {
  /** ID of the entitlement type */
  id: string
  /** Human readable description of the entitlement. */
  description: string | null
}

export interface RequestMarketplaceInstallationEntitlement {

}
