// This file is automatically generated based on the Looker Core API metadata.

export interface MarketplaceListingVersion {
  /** Human-readable label representing the current version number. This is not guaranteed to be in any particular format. */
  number: string
  /** An ISO-8601 formatted string representing the release date of this version. */
  released_at: string
  /** Description of the listing, in Markdown format. */
  release_notes_md: string | null
  /** The Git URI of the repository containing the code for this version. */
  project_git_uri: string
  /** The Git `ref` representing the code for this version. */
  project_git_ref: string
  /** Required version of Looker in semver format (e.g. ">=6.20.0") */
  looker_version: string
}

export interface RequestMarketplaceListingVersion {

}
