// This file is automatically generated based on the Looker Core API metadata.

import { MarketplaceCategory } from './marketplace_category'
import { MarketplaceCollection } from './marketplace_collection'
import { MarketplaceListing } from './marketplace_listing'

export interface MarketplaceData {
  /** An array of all marketplace listings. */
  listings: MarketplaceListing[]
  /** An array of all marketplace categories. */
  categories: MarketplaceCategory[]
  /** An array of all marketplace collections. */
  collections: MarketplaceCollection[]
}

export interface RequestMarketplaceData {

}
