// This file is automatically generated based on the Looker Core API metadata.

export interface MarketplaceListingAuthor {
  /** Unique ID of the author */
  id: string
  /** Human-readable label for the author */
  label: string
}

export interface RequestMarketplaceListingAuthor {

}
