// This file is automatically generated based on the Looker Core API metadata.

export interface MarketplaceCategory {
  /** The ID of the category. */
  id: string
  /** Human-readable label for the category */
  label: string
  /** Human-readable description for the category */
  description: string
  /** URI for an image representing the category icon. */
  icon_uri: string
}

export interface RequestMarketplaceCategory {

}
