// This file is automatically generated based on the Looker Core API metadata.

import { MarketplaceConstant, RequestMarketplaceConstant } from './marketplace_constant'

export interface MarketplaceConfiguration {
  /** Constants for the given marketplace installation */
  constants: MarketplaceConstant[] | null
}

export interface RequestMarketplaceConfiguration {
  /** Constants for the given marketplace installation */
  constants?: RequestMarketplaceConstant[] | null
}
