// This file is automatically generated based on the Looker Core API metadata.

import { MarketplaceBranding } from './marketplace_branding'
import { MarketplaceCategory } from './marketplace_category'
import { MarketplaceConnectionHubDetails } from './marketplace_connection_hub_details'
import { MarketplaceListingAuthor } from './marketplace_listing_author'
import { MarketplaceListingMetadataField } from './marketplace_listing_metadata_field'
import { MarketplaceListingVersion } from './marketplace_listing_version'

export interface MarketplaceListing {
  /** Operations the current user is able to perform on this object */
  can: {[key: string]: boolean}
  /** Unique ID of the listing */
  id: string
  /** Human-readable label of the listing */
  label: string
  /** Details about the author of the listing. */
  author: MarketplaceListingAuthor | null
  /** An array of all of the available versions of this listing, ordered with the latest version first. */
  versions: MarketplaceListingVersion[]
  /** An array of URIs representing screenshots or images of the listing. */
  hero_image_uris: string[]
  /** An array of arbitrary metadata fields representing detailed information about the listing to be presented to users. */
  metadata_fields: MarketplaceListingMetadataField[]
  /** Primary description of the listing, in Markdown format. */
  description_md: string
  /** A URI where users can go to learn more about how to use the listing's contents. */
  documentation_uri: string | null
  /** A URI where users can go to for support regarding the listing's contents. */
  support_uri: string | null
  /** Details about the category of the listing. */
  category: MarketplaceCategory | null
  /** Details about the branding of the listing. */
  branding: MarketplaceBranding
  /** An alternate label for the install button, such as "Install Beta" or "Try for Free". If null, a default label will appear. */
  install_button_label: string | null
  /** A short description that will be displayed near the install button, to provide additional context about the install process, such as describing the limitations of the beta or the length of a free trial. If null, no description will appear. */
  install_description: string | null
  /** Details about the connection hub processing for the listing. Set to null if data is not available in Connection Hub. */
  connection_hub_details: MarketplaceConnectionHubDetails | null
  /** Null if the listing can be installed, otherwise contains a human-readable reason why not. */
  install_unavailable_reason: string | null
}

export interface RequestMarketplaceListing {

}
