// This file is automatically generated based on the Looker Core API metadata.

export interface MarketplaceInstallationAcceptLicenseParams {
  /** Text of the license to accept. */
  license_text: string | null
}

export interface RequestMarketplaceInstallationAcceptLicenseParams {
  /** Text of the license to accept. */
  license_text?: string | null
}
