// This file is automatically generated based on the Looker Core API metadata.

export interface MarketplaceListingMetadataField {
  /** Unique ID of the field */
  id: string
  /** Human-readable label for the field */
  label: string
  /** Human-readable list of values for this metadata field. */
  values: string[]
}

export interface RequestMarketplaceListingMetadataField {

}
