// This file is automatically generated based on the Looker Core API metadata.

export interface MarketplaceBranding {
  /** Abbreviated description, in Markdown format. */
  tagline: string
  /** A short descriptive badge, like "Beta" or "New!". If null, no badge will be displayed. */
  badge: string | null
  /** A CSS color string that represents the brand color. If null, a default visual appearance will be used. */
  brand_color: string | null
  /** URI for an image representing the logo. If null, a default visual appearance will be used. */
  image_uri: string | null
}

export interface RequestMarketplaceBranding {

}
