// This file is automatically generated based on the Looker Core API metadata.

export enum MarketplaceConstantValueConstraint {
  None = 'none',
  Connection = 'connection'
}

export interface MarketplaceConstant {
  /** Name of the constant */
  name: string
  /** Default value for the constant */
  default_value: string | null
  /** Value of the constant */
  value: string | null
  /** Whether the constant needs to be provided */
  required: boolean
  /** Label for the constant */
  label: string
  /** Description for the constant */
  description: string | null
  /** Name of the type of value constraint this constant uses to validate its values. Valid values are: "none", "connection". */
  value_constraint: MarketplaceConstantValueConstraint | null
}

export interface RequestMarketplaceConstant {
  /** Name of the constant */
  name?: string
  /** Value of the constant */
  value?: string | null
}
