// This file is automatically generated based on the Looker Core API metadata.

export interface MarketplaceConnectionHubDetails {
  /** Override human-readable prompt to use connection hub. Markdown is supported. */
  connection_hub_prompt: string | null
  /** Override human-readable selection label to indicate that connection hub is to be used. */
  connection_hub_yes_label: string | null
  /** Override human-readable selection label to indicate that connection hub is NOT to be used. */
  connection_hub_no_label: string | null
  /** Override human-readable warning message displayed when user selects connection hub is NOT to be used.. Markdown is supported but it should be kept simple. */
  connection_hub_no_warning: string | null
  /** Override human-readable prompt to use existing connection hub connection. Markdown is supported. */
  existing_connection_prompt: string | null
  /** Override human-readable selection label to indicate that existing connection hub connection is to be used. */
  existing_connection_yes_label: string | null
  /** Override human-readable selection label to indicate that existing connection hub connection is NOT to be used. */
  existing_connection_no_label: string | null
  /** Override title of dialog that indicates that further LookML configurations is required. */
  post_install_title: string | null
  /** Override description of dialog that indicates that further LookML configurations is required. */
  post_install_description: string | null
}

export interface RequestMarketplaceConnectionHubDetails {

}
