// This file is automatically generated based on the Looker Core API metadata.

import { MarketplaceBranding } from './marketplace_branding'
import { MarketplaceConstant } from './marketplace_constant'
import { MarketplaceInstallationEntitlement } from './marketplace_installation_entitlement'

export interface MarketplaceInstallation {
  /** Operations the current user is able to perform on this object */
  can: {[key: string]: boolean}
  /** Unique ID of the install */
  id: number
  /** ID of the associated marketplace listing, if there is one */
  marketplace_listing_id: string | null
  /** ID of the associated project, if there is one */
  project_id: string | null
  /** Constants for the given marketplace installation */
  constants: MarketplaceConstant[] | null
  /** Whether the project associated with this installation is available in production mode. */
  deployed: boolean
  /** Whether changes have been made to the installation that have not yet been deployed. These changes can be either deployed or abandoned. */
  needs_deploy: boolean
  /** A list of the entitlements that this installation requires. */
  requested_entitlements: MarketplaceInstallationEntitlement[] | null
  /** A list of IDs of the entitlements that have been accepted for this installation. */
  accepted_entitlement_ids: string[] | null
  /** True when all the requested entitlements have been accepted. */
  has_accepted_entitlements: boolean
  /** Label of the category of the installation. */
  category_label: string | null
  /** Label of the installation. */
  label: string | null
  /** Details about the branding of the installation. */
  branding: MarketplaceBranding | null
  /** Human-readable number of the version of the installation that is deployed to production. This number's format should not be relied on. */
  production_version_number: string
  /** Whether an update is available for the version of the installation that is deployed to production. */
  update_available: boolean
  /** Text of the license for this installation. */
  license_text: string | null
  /** True when the license has been accepted. */
  has_accepted_license: boolean
}

export interface RequestMarketplaceInstallation {

}
