// This file is automatically generated based on the Looker Core API metadata.

import { DashboardBase } from './dashboard_base'
import { LookmlModel } from './lookml_model'
import { MarketplaceInstallation } from './marketplace_installation'
import { ThinDataApp } from './thin_data_app'

export interface MarketplaceInstallationContent {
  /** The installation that contains the content. */
  installation: MarketplaceInstallation
  /** Applications that this installation contains. */
  applications: ThinDataApp[]
  /** Dashboards that this installation contains. */
  dashboards: DashboardBase[]
  /** Models that this installation contains. */
  models: LookmlModel[]
}

export interface RequestMarketplaceInstallationContent {

}
