// This file is automatically generated based on the Looker Core API metadata.

export interface MergeFields {
  /** Field name to map onto in the merged results */
  field_name: string | null
  /** Field name from the source query */
  source_field_name: string | null
}

export interface RequestMergeFields {
  /** Field name to map onto in the merged results */
  field_name?: string | null
  /** Field name from the source query */
  source_field_name?: string | null
}
