// This file is automatically generated based on the Looker Core API metadata.

import { MergeFields, RequestMergeFields } from './merge_fields'

export interface MergeQuerySourceQuery {
  /** An array defining which fields of the source query are mapped onto fields of the merge query */
  merge_fields: MergeFields[] | null
  /** Display name */
  name: string | null
  /** Id of the query to merge */
  query_id: number | null
}

export interface RequestMergeQuerySourceQuery {
  /** An array defining which fields of the source query are mapped onto fields of the merge query */
  merge_fields?: RequestMergeFields[] | null
  /** Display name */
  name?: string | null
  /** Id of the query to merge */
  query_id?: number | null
}
