// This file is automatically generated based on the Looker Core API metadata.

export interface ModelsNotValidated {
  /** Model name */
  name: string | null
  /** Project file */
  project_file_id: string | null
}

export interface RequestModelsNotValidated {

}
