// This file is automatically generated based on the Looker Core API metadata.

export interface OIDCGroupWrite {
  /** Name of group in OIDC */
  name: string | null
  /** Looker Role Ids */
  role_ids: number[] | null
  /** Operations the current user is able to perform on this object */
  can: {[key: string]: boolean}
}

export interface RequestOIDCGroupWrite {
  /** Name of group in OIDC */
  name?: string | null
  /** Looker Role Ids */
  role_ids?: number[] | null
}
