// This file is automatically generated based on the Looker Core API metadata.

import { Role } from './role'

export interface OIDCGroupRead {
  /** Name of group in OIDC */
  name: string | null
  /** Looker Roles */
  roles: Role[] | null
}

export interface RequestOIDCGroupRead {

}
