// This file is automatically generated based on the Looker Core API metadata.

import { UserAttribute } from './user_attribute'

export interface OIDCUserAttributeRead {
  /** Name of User Attribute in OIDC */
  name: string | null
  /** Required to be in OIDC assertion for login to be allowed to succeed */
  required: boolean
  /** Looker User Attributes */
  user_attributes: UserAttribute[] | null
}

export interface RequestOIDCUserAttributeRead {

}
