// This file is automatically generated based on the Looker Core API metadata.

export interface PasswordConfig {
  /** Operations the current user is able to perform on this object */
  can: {[key: string]: boolean}
  /** Minimum number of characters required for a new password.  Must be between 7 and 100 */
  min_length: number | null
  /** Require at least one numeric character */
  require_numeric: boolean
  /** Require at least one uppercase and one lowercase letter */
  require_upperlower: boolean
  /** Require at least one special character */
  require_special: boolean
}

export interface RequestPasswordConfig {
  /** Minimum number of characters required for a new password.  Must be between 7 and 100 */
  min_length?: number | null
  /** Require at least one numeric character */
  require_numeric?: boolean
  /** Require at least one uppercase and one lowercase letter */
  require_upperlower?: boolean
  /** Require at least one special character */
  require_special?: boolean
}
