// This file is automatically generated based on the Looker Core API metadata.

export interface PermissionSet {
  /** Operations the current user is able to perform on this object */
  can: {[key: string]: boolean}
  all_access: boolean
  built_in: boolean
  /** Unique Id */
  id: number
  /** Name of PermissionSet */
  name: string | null
  permissions: string[] | null
  /** Link to get this item */
  url: string | null
}

export interface RequestPermissionSet {
  /** Name of PermissionSet */
  name?: string | null
  permissions?: string[] | null
}
