// This file is automatically generated based on the Looker Core API metadata.

export interface Permission {
  /** Operations the current user is able to perform on this object */
  can: {[key: string]: boolean}
  /** Permission symbol */
  permission: string | null
  /** Dependency parent symbol */
  parent: string | null
  /** Description */
  description: string | null
}

export interface RequestPermission {

}
