// This file is automatically generated based on the Looker Core API metadata.

export interface PrefetchAccessFilterValue {
  /** Operations the current user is able to perform on this object */
  can: {[key: string]: boolean}
  /** Access filter field name. */
  field: string | null
  /** Access filter model name. */
  model: string | null
  /** Access filter value */
  value: string | null
}

export interface RequestPrefetchAccessFilterValue {

}
