// This file is automatically generated based on the Looker Core API metadata.

export interface PrefetchDashboardFilterValue {
  /** Operations the current user is able to perform on this object */
  can: {[key: string]: boolean}
  /** Dashboard filter name. */
  name: string | null
  /** Dashboard filter value */
  value: string | null
}

export interface RequestPrefetchDashboardFilterValue {

}
