// This file is automatically generated based on the Looker Core API metadata.

export enum ProjectPullRequestMode {
  Off = 'off',
  Links = 'links',
  Recommended = 'recommended',
  Required = 'required'
}

export interface Project {
  /** Operations the current user is able to perform on this object */
  can: {[key: string]: boolean}
  /** Project Id */
  id: string
  /** Project display name */
  name: string
  /** If true the project is configured with a git repository */
  uses_git: boolean
  /** Git remote repository url */
  git_remote_url: string | null
  /** Git username for HTTPS authentication. (For production only, if using user attributes.) */
  git_username: string | null
  /** User attribute name for username in per-user HTTPS authentication. */
  git_username_user_attribute: string | null
  /** User attribute name for password in per-user HTTPS authentication. */
  git_password_user_attribute: string | null
  /** Name of the git service provider */
  git_service_name: string | null
  /** The git pull request policy for this project. Valid values are: "off", "links", "recommended", "required". */
  pull_request_mode: ProjectPullRequestMode
  /** Validation policy: If true, the project must pass validation checks before project changes can be committed to the git repository */
  validation_required: boolean
  /** If true, folders are enabled for this project */
  folders_enabled: boolean
  /** Validation policy: If true, the project can be committed with warnings when `validation_required` is true. (`allow_warnings` does nothing if `validation_required` is false). */
  allow_warnings: boolean
  /** If true the project is an example project and cannot be modified */
  is_example: boolean
}

export interface RequestProject {
  /** Project display name */
  name?: string
  /** Git remote repository url */
  git_remote_url?: string | null
  /** Git username for HTTPS authentication. (For production only, if using user attributes.) */
  git_username?: string | null
  /** (Write-Only) Git password for HTTPS authentication. (For production only, if using user attributes.) */
  git_password?: string | null
  /** User attribute name for username in per-user HTTPS authentication. */
  git_username_user_attribute?: string | null
  /** User attribute name for password in per-user HTTPS authentication. */
  git_password_user_attribute?: string | null
  /** Name of the git service provider */
  git_service_name?: string | null
  /** (Write-Only) Optional secret token with which to authenticate requests to the webhook deploy endpoint. If not set, endpoint is unauthenticated. */
  deploy_secret?: string | null
  /** (Write-Only) When true, unsets the deploy secret to allow unauthenticated access to the webhook deploy endpoint. */
  unset_deploy_secret?: boolean
  /** The git pull request policy for this project. Valid values are: "off", "links", "recommended", "required". */
  pull_request_mode?: ProjectPullRequestMode
  /** Validation policy: If true, the project must pass validation checks before project changes can be committed to the git repository */
  validation_required?: boolean
  /** If true, folders are enabled for this project */
  folders_enabled?: boolean
  /** Validation policy: If true, the project can be committed with warnings when `validation_required` is true. (`allow_warnings` does nothing if `validation_required` is false). */
  allow_warnings?: boolean
}
