// This file is automatically generated based on the Looker Core API metadata.

export interface ProjectError {
  /** A stable token that uniquely identifies this class of error, ignoring parameter values. Error message text may vary due to parameters or localization, but error codes do not. For example, a "File not found" error will have the same error code regardless of the filename in question or the user's display language */
  code: string | null
  /** Severity: fatal, error, warning, info, success */
  severity: string | null
  /** Error classification: syntax, deprecation, model_configuration, etc */
  kind: string | null
  /** Error message which may contain information such as dashboard or model names that may be considered sensitive in some use cases. Avoid storing or sending this message outside of Looker */
  message: string | null
  /** The field associated with this error */
  field_name: string | null
  /** Name of the file containing this error */
  file_path: string | null
  /** Line number in the file of this error */
  line_number: number | null
  /** The model associated with this error */
  model_id: string | null
  /** The explore associated with this error */
  explore: string | null
  /** A link to Looker documentation about this error */
  help_url: string | null
  /** Error parameters */
  params: {[key: string]: string} | null
  /** A version of the error message that does not contain potentially sensitive information. Suitable for situations in which messages are stored or sent to consumers outside of Looker, such as external logs. Sanitized messages will display "(?)" where sensitive information would appear in the corresponding non-sanitized message */
  sanitized_message: string | null
}

export interface RequestProjectError {

}
