// This file is automatically generated based on the Looker Core API metadata.

import { GitBranch } from './git_branch'

export interface ProjectWorkspace {
  /** Operations the current user is able to perform on this object */
  can: {[key: string]: boolean}
  /** The id of the project */
  project_id: string | null
  /** The id of the local workspace containing the project files */
  workspace_id: string | null
  /** The status of the local git directory */
  git_status: string | null
  /** Git head revision name */
  git_head: string | null
  /** GitBranch */
  git_branch: GitBranch | null
  /** The lookml syntax used by all files in this project */
  lookml_type: string | null
}

export interface RequestProjectWorkspace {

}
