// This file is automatically generated based on the Looker Core API metadata.

import { ModelsNotValidated } from './models_not_validated'
import { ProjectError } from './project_error'

export interface ProjectValidationCache {
  /** A list of project errors */
  errors: ProjectError[] | null
  /** A hash value computed from the project's current state */
  project_digest: string | null
  /** A list of models which were not fully validated */
  models_not_validated: ModelsNotValidated[] | null
  /** Duration of project validation in seconds */
  computation_time: number | null
  /** If true, the cached project validation results are no longer accurate because the project has changed since the cached results were calculated */
  stale: boolean
}

export interface RequestProjectValidationCache {

}
