// This file is automatically generated based on the Looker Core API metadata.

import { Query } from './query'

export interface QueryTask {
  /** Operations the current user is able to perform on this object */
  can: {[key: string]: boolean}
  /** Unique Id */
  id: string
  /** Id of query */
  query_id: number | null
  /** Query */
  query: Query | null
  /** whether or not to generate links in the query response. */
  generate_links: boolean
  /** Use production models to run query (even is user is in dev mode). */
  force_production: boolean
  /** Prefix to use for drill links. */
  path_prefix: string | null
  /** Whether or not to use the cache */
  cache: boolean
  /** Whether or not to run table calculations on the server */
  server_table_calcs: boolean
  /** Retrieve any results from cache even if the results have expired. */
  cache_only: boolean
  /** cache key used to cache query. */
  cache_key: string | null
  /** Status of query task. */
  status: string | null
  /** Source of query task. */
  source: string | null
  /** Runtime of prior queries. */
  runtime: number | null
  /** Rebuild PDTS used in query. */
  rebuild_pdts: boolean
  /** Source of the results of the query. */
  result_source: string | null
  /** Id of look associated with query. */
  look_id: number | null
  /** Id of dashboard associated with query. */
  dashboard_id: string | null
  /** The data format of the query results. */
  result_format: string | null
}

export interface RequestQueryTask {
  /** Id of query */
  query_id?: number | null
  /** whether or not to generate links in the query response. */
  generate_links?: boolean
  /** Use production models to run query (even is user is in dev mode). */
  force_production?: boolean
  /** Prefix to use for drill links. */
  path_prefix?: string | null
  /** Whether or not to use the cache */
  cache?: boolean
  /** Whether or not to run table calculations on the server */
  server_table_calcs?: boolean
  /** Retrieve any results from cache even if the results have expired. */
  cache_only?: boolean
  /** Status of query task. */
  status?: string | null
  /** Source of query task. */
  source?: string | null
  /** Rebuild PDTS used in query. */
  rebuild_pdts?: boolean
  /** Id of look associated with query. */
  look_id?: number | null
  /** Id of dashboard associated with query. */
  dashboard_id?: string | null
}
