// This file is automatically generated based on the Looker Core API metadata.

export interface RenderTask {
  /** Operations the current user is able to perform on this object */
  can: {[key: string]: boolean}
  /** Date/Time render task was created */
  created_at: string | null
  /** Filter values to apply to the dashboard queries, in URL query format */
  dashboard_filters: string | null
  /** Id of dashboard to render */
  dashboard_id: number | null
  /** Dashboard layout style: single_column or tiled */
  dashboard_style: string | null
  /** Date/Time render task was completed */
  finalized_at: string | null
  /** Output height in pixels. Flowed layouts may ignore this value. */
  height: number | null
  /** Id of this render task */
  id: string
  /** Id of look to render */
  look_id: number | null
  /** Id of lookml dashboard to render */
  lookml_dashboard_id: string | null
  /** Id of query to render */
  query_id: number | null
  /** Number of seconds elapsed running queries */
  query_runtime: number | null
  /** Number of seconds elapsed rendering data */
  render_runtime: number | null
  /** Output format: pdf, png, or jpg */
  result_format: string | null
  /** Total seconds elapsed for render task */
  runtime: number | null
  /** Render task status: enqueued_for_query, querying, enqueued_for_render, rendering, success, failure */
  status: string | null
  /** Additional information about the current status */
  status_detail: string | null
  /** The user account permissions in which the render task will execute */
  user_id: number | null
  /** Output width in pixels */
  width: number | null
}

export interface RequestRenderTask {

}
