// This file is automatically generated based on the Looker Core API metadata.

export interface RepositoryCredential {
  /** Operations the current user is able to perform on this object */
  can: {[key: string]: boolean}
  /** Unique Id */
  id: string
  /** Root project Id */
  root_project_id: string
  /** Git remote repository url */
  remote_url: string
  /** Git username for HTTPS authentication. */
  git_username: string | null
  /** Public deploy key for SSH authentication. */
  ssh_public_key: string | null
  /** Whether the credentials have been configured for the Git Repository. */
  is_configured: boolean
}

export interface RequestRepositoryCredential {
  /** Git username for HTTPS authentication. */
  git_username?: string | null
  /** (Write-Only) Git password for HTTPS authentication. */
  git_password?: string | null
  /** Public deploy key for SSH authentication. */
  ssh_public_key?: string | null
}
