// This file is automatically generated based on the Looker Core API metadata.

import { ModelSet } from './model_set'
import { PermissionSet } from './permission_set'

export interface Role {
  /** Operations the current user is able to perform on this object */
  can: {[key: string]: boolean}
  /** Unique Id */
  id: number
  /** Name of Role */
  name: string | null
  /** (Read only) Permission set */
  permission_set: PermissionSet | null
  /** (Read only) Model set */
  model_set: ModelSet | null
  /** Link to get this item */
  url: string | null
  /** Link to get list of users with this role */
  users_url: string | null
}

export interface RequestRole {
  /** Name of Role */
  name?: string | null
  /** (Write-Only) Id of permission set */
  permission_set_id?: number | null
  /** (Write-Only) Id of model set */
  model_set_id?: number | null
}
