// This file is automatically generated based on the Looker Core API metadata.

import { Role } from './role'

export interface SamlGroupRead {
  /** Name of group in Saml */
  name: string | null
  /** Looker Roles */
  roles: Role[] | null
  /** Link to saml config */
  url: string | null
}

export interface RequestSamlGroupRead {

}
