// This file is automatically generated based on the Looker Core API metadata.

import { Group } from './group'
import { Role } from './role'
import { SamlGroupRead } from './saml_group_read'
import { RequestSamlGroupWrite, SamlGroupWrite } from './saml_group_write'
import { SamlUserAttributeRead } from './saml_user_attribute_read'
import { RequestSamlUserAttributeWrite, SamlUserAttributeWrite } from './saml_user_attribute_write'

export interface SamlConfig {
  /** Operations the current user is able to perform on this object */
  can: {[key: string]: boolean}
  /** Enable/Disable Saml authentication for the server */
  enabled: boolean
  /** Identity Provider Certificate (provided by IdP) */
  idp_cert: string | null
  /** Identity Provider Url (provided by IdP) */
  idp_url: string | null
  /** Identity Provider Issuer (provided by IdP) */
  idp_issuer: string | null
  /** Identity Provider Audience (set in IdP config). Optional in Looker. Set this only if you want Looker to validate the audience value returned by the IdP. */
  idp_audience: string | null
  /** Count of seconds of clock drift to allow when validating timestamps of assertions. */
  allowed_clock_drift: number | null
  /** Name of user record attributes used to indicate email address field */
  user_attribute_map_email: string | null
  /** Name of user record attributes used to indicate first name */
  user_attribute_map_first_name: string | null
  /** Name of user record attributes used to indicate last name */
  user_attribute_map_last_name: string | null
  /** Merge first-time saml login to existing user account by email addresses. When a user logs in for the first time via saml this option will connect this user into their existing account by finding the account with a matching email address by testing the given types of credentials for existing users. Otherwise a new user account will be created for the user. This list (if provided) must be a comma separated list of string like 'email,ldap,google' */
  new_user_migration_types: string | null
  /** Allow alternate email-based login via '/login/email' for admins and for specified users with the 'login_special_email' permission. This option is useful as a fallback during ldap setup, if ldap config problems occur later, or if you need to support some users who are not in your ldap directory. Looker email/password logins are always disabled for regular users when ldap is enabled. */
  alternate_email_login_allowed: boolean
  /** Slug to identify configurations that are created in order to run a Saml config test */
  test_slug: string | null
  /** When this config was last modified */
  modified_at: string | null
  /** User id of user who last modified this config */
  modified_by: string | null
  /** (Read-only) Roles that will be applied to new users the first time they login via Saml */
  default_new_user_roles: Role[] | null
  /** (Read-only) Groups that will be applied to new users the first time they login via Saml */
  default_new_user_groups: Group[] | null
  /** Set user roles in Looker based on groups from Saml */
  set_roles_from_groups: boolean
  /** Name of user record attributes used to indicate groups. Used when 'groups_finder_type' is set to 'grouped_attribute_values' */
  groups_attribute: string | null
  /** (Read-only) Array of mappings between Saml Groups and Looker Roles */
  groups: SamlGroupRead[] | null
  /** (Read/Write) Array of mappings between Saml Groups and arrays of Looker Role ids */
  groups_with_role_ids: SamlGroupWrite[] | null
  /** Users will not be allowed to login at all unless a role for them is found in Saml if set to true */
  auth_requires_role: boolean
  /** (Read-only) Array of mappings between Saml User Attributes and Looker User Attributes */
  user_attributes: SamlUserAttributeRead[] | null
  /** (Read/Write) Array of mappings between Saml User Attributes and arrays of Looker User Attribute ids */
  user_attributes_with_ids: SamlUserAttributeWrite[] | null
  /** Identifier for a strategy for how Looker will find groups in the SAML response. One of ['grouped_attribute_values', 'individual_attributes'] */
  groups_finder_type: string | null
  /** Value for group attribute used to indicate membership. Used when 'groups_finder_type' is set to 'individual_attributes' */
  groups_member_value: string | null
  /** Bypass the login page when user authentication is required. Redirect to IdP immediately instead. */
  bypass_login_page: boolean
  /** Link to get this item */
  url: string | null
}

export interface RequestSamlConfig {
  /** Enable/Disable Saml authentication for the server */
  enabled?: boolean
  /** Identity Provider Certificate (provided by IdP) */
  idp_cert?: string | null
  /** Identity Provider Url (provided by IdP) */
  idp_url?: string | null
  /** Identity Provider Issuer (provided by IdP) */
  idp_issuer?: string | null
  /** Identity Provider Audience (set in IdP config). Optional in Looker. Set this only if you want Looker to validate the audience value returned by the IdP. */
  idp_audience?: string | null
  /** Count of seconds of clock drift to allow when validating timestamps of assertions. */
  allowed_clock_drift?: number | null
  /** Name of user record attributes used to indicate email address field */
  user_attribute_map_email?: string | null
  /** Name of user record attributes used to indicate first name */
  user_attribute_map_first_name?: string | null
  /** Name of user record attributes used to indicate last name */
  user_attribute_map_last_name?: string | null
  /** Merge first-time saml login to existing user account by email addresses. When a user logs in for the first time via saml this option will connect this user into their existing account by finding the account with a matching email address by testing the given types of credentials for existing users. Otherwise a new user account will be created for the user. This list (if provided) must be a comma separated list of string like 'email,ldap,google' */
  new_user_migration_types?: string | null
  /** Allow alternate email-based login via '/login/email' for admins and for specified users with the 'login_special_email' permission. This option is useful as a fallback during ldap setup, if ldap config problems occur later, or if you need to support some users who are not in your ldap directory. Looker email/password logins are always disabled for regular users when ldap is enabled. */
  alternate_email_login_allowed?: boolean
  /** (Write-Only) Array of ids of roles that will be applied to new users the first time they login via Saml */
  default_new_user_role_ids?: number[] | null
  /** (Write-Only) Array of ids of groups that will be applied to new users the first time they login via Saml */
  default_new_user_group_ids?: number[] | null
  /** Set user roles in Looker based on groups from Saml */
  set_roles_from_groups?: boolean
  /** Name of user record attributes used to indicate groups. Used when 'groups_finder_type' is set to 'grouped_attribute_values' */
  groups_attribute?: string | null
  /** (Read/Write) Array of mappings between Saml Groups and arrays of Looker Role ids */
  groups_with_role_ids?: RequestSamlGroupWrite[] | null
  /** Users will not be allowed to login at all unless a role for them is found in Saml if set to true */
  auth_requires_role?: boolean
  /** (Read/Write) Array of mappings between Saml User Attributes and arrays of Looker User Attribute ids */
  user_attributes_with_ids?: RequestSamlUserAttributeWrite[] | null
  /** Identifier for a strategy for how Looker will find groups in the SAML response. One of ['grouped_attribute_values', 'individual_attributes'] */
  groups_finder_type?: string | null
  /** Value for group attribute used to indicate membership. Used when 'groups_finder_type' is set to 'individual_attributes' */
  groups_member_value?: string | null
  /** Bypass the login page when user authentication is required. Redirect to IdP immediately instead. */
  bypass_login_page?: boolean
}
