// This file is automatically generated based on the Looker Core API metadata.

export interface SamlGroupWrite {
  /** Name of group in Saml */
  name: string | null
  /** Looker Role Ids */
  role_ids: number[] | null
  /** Link to saml config */
  url: string | null
}

export interface RequestSamlGroupWrite {
  /** Name of group in Saml */
  name?: string | null
  /** Looker Role Ids */
  role_ids?: number[] | null
}
