// This file is automatically generated based on the Looker Core API metadata.

export interface SamlUserAttributeWrite {
  /** Name of User Attribute in Saml */
  name: string | null
  /** Required to be in Saml assertion for login to be allowed to succeed */
  required: boolean
  /** Looker User Attribute Ids */
  user_attribute_ids: number[] | null
  /** Link to saml config */
  url: string | null
}

export interface RequestSamlUserAttributeWrite {
  /** Name of User Attribute in Saml */
  name?: string | null
  /** Required to be in Saml assertion for login to be allowed to succeed */
  required?: boolean
  /** Looker User Attribute Ids */
  user_attribute_ids?: number[] | null
}
