// This file is automatically generated based on the Looker Core API metadata.

import { UserAttribute } from './user_attribute'

export interface SamlUserAttributeRead {
  /** Name of User Attribute in Saml */
  name: string | null
  /** Required to be in Saml assertion for login to be allowed to succeed */
  required: boolean
  /** Looker User Attributes */
  user_attributes: UserAttribute[] | null
  /** Link to saml config */
  url: string | null
}

export interface RequestSamlUserAttributeRead {

}
