// This file is automatically generated based on the Looker Core API metadata.

export interface ScheduledJobStage {
  /** Unique Id */
  id: number
  /** Job this stage describes */
  scheduled_job_id: number | null
  /** Node Id stage was run on */
  node_id: number | null
  /** Stage */
  stage: string | null
  /** Time when the stage was started */
  started_at: string | null
  /** Time whent the stage was completed */
  completed_at: string | null
}

export interface RequestScheduledJobStage {

}
