// This file is automatically generated based on the Looker Core API metadata.

export interface ScheduledJobDestination {
  /** Unique Id */
  id: number
  /** Id of scheduled job */
  scheduled_job_id: number | null
  /** Format requested by the given destination (i.e. PDF, etc.) */
  format: string | null
  /** Address for recipient (only email addresses supported for now) */
  address: string | null
  /** Type of the address (only 'email' is supported for now) */
  type: string | null
}

export interface RequestScheduledJobDestination {

}
