// This file is automatically generated based on the Looker Core API metadata.

import { ScheduledJobDestination } from './scheduled_job_destination'
import { ScheduledJobStage } from './scheduled_job_stage'
import { ScheduledPlan } from './scheduled_plan'
import { UserPublic } from './user_public'

export interface ScheduledJob {
  /** Operations the current user is able to perform on this object */
  can: {[key: string]: boolean}
  /** Unique Id */
  id: number
  /** Status of the job */
  status: string | null
  /** Optional message describing status of the job */
  status_detail: string | null
  /** Detailed information about the job stage */
  scheduled_job_stage: ScheduledJobStage[] | null
  /** Whether the row limit was reached when running */
  row_limit_reached: string | null
  /** When the ScheduledJob started */
  created_at: string | null
  /** When the ScheduledJob finished */
  finalized_at: string | null
  /** User who owns this ScheduledPlan */
  user: UserPublic | null
  /** Id of a look */
  look_id: number | null
  /** Id of a dashboard */
  dashboard_id: number | null
  /** Id of a LookML dashboard */
  lookml_dashboard_id: string | null
  /** Delivery should occur if running the dashboard or look returns results */
  require_results: boolean
  /** Delivery should occur if the dashboard look does not return results */
  require_no_results: boolean
  /** Delivery should occur if data have changed since the last run */
  require_change: boolean
  /** Will run an unlimited query and send all results. */
  send_all_results: boolean
  /** Vixie-Style crontab specification when to run */
  crontab: string | null
  /** Name of a datagroup; if specified will run when datagroup triggered (can't be used with cron string) */
  datagroup: string | null
  /** Timezone for interpreting the specified crontab (default is Looker instance timezone) */
  timezone: string | null
  /** Used for caching */
  data_slug: string | null
  /** Used for caching */
  data_signature: string | null
  /** Name */
  name: string | null
  /** Title */
  title: string | null
  /** Query id */
  query_id: string | null
  /** Scheduled job destinations */
  scheduled_job_destination: ScheduledJobDestination[] | null
  /** ScheduledPlan id that initiated the ScheduledJob */
  scheduled_plan_id: number | null
  /** ScheduledPlan that initiated the ScheduledJob */
  scheduled_plan: ScheduledPlan | null
  /** Runtime in seconds */
  runtime: number | null
  /** Url for the scheduled entity */
  looker_url: string | null
  /** Whether the plan in question was only run once (usually for testing) */
  run_once: boolean
  /** Whether links back to Looker should be included in this ScheduledJob */
  include_links: boolean
  /** The size of paper a PDF should be rendered for */
  pdf_paper_size: string | null
  /** Whether the paper should be landscape */
  pdf_landscape: boolean
}

export interface RequestScheduledJob {

}
