// This file is automatically generated based on the Looker Core API metadata.

export interface ScheduledPlanDestination {
  /** Unique Id */
  id: number
  /** Id of a scheduled plan you own */
  scheduled_plan_id: number | null
  /** The data format to send to the given destination. Supported formats vary by destination, but include: "txt", "csv", "inline_json", "json", "json_detail", "xlsx", "html", "wysiwyg_pdf", "assembled_pdf", "wysiwyg_png" */
  format: string | null
  /** Are values formatted? (containing currency symbols, digit separators, etc. */
  apply_formatting: boolean
  /** Whether visualization options are applied to the results. */
  apply_vis: boolean
  /** Address for recipient. For email e.g. 'user@example.com'. For webhooks e.g. 'https://domain/path'. For Amazon S3 e.g. 's3://bucket-name/path/'. For SFTP e.g. 'sftp://host-name/path/'.  */
  address: string | null
  /** Whether the recipient is a Looker user on the current instance (only applicable for email recipients) */
  looker_recipient: boolean
  /** Type of the address ('email', 'webhook', 's3', or 'sftp') */
  type: string | null
  /** JSON object containing parameters for external scheduling. For Amazon S3, this requires keys and values for access_key_id and region. For SFTP, this requires a key and value for username. */
  parameters: string | null
  /** Optional message to be included in scheduled emails */
  message: string | null
}

export interface RequestScheduledPlanDestination {
  /** Id of a scheduled plan you own */
  scheduled_plan_id?: number | null
  /** The data format to send to the given destination. Supported formats vary by destination, but include: "txt", "csv", "inline_json", "json", "json_detail", "xlsx", "html", "wysiwyg_pdf", "assembled_pdf", "wysiwyg_png" */
  format?: string | null
  /** Are values formatted? (containing currency symbols, digit separators, etc. */
  apply_formatting?: boolean
  /** Whether visualization options are applied to the results. */
  apply_vis?: boolean
  /** Address for recipient. For email e.g. 'user@example.com'. For webhooks e.g. 'https://domain/path'. For Amazon S3 e.g. 's3://bucket-name/path/'. For SFTP e.g. 'sftp://host-name/path/'.  */
  address?: string | null
  /** Type of the address ('email', 'webhook', 's3', or 'sftp') */
  type?: string | null
  /** JSON object containing parameters for external scheduling. For Amazon S3, this requires keys and values for access_key_id and region. For SFTP, this requires a key and value for username. */
  parameters?: string | null
  /** (Write-Only) JSON object containing secret parameters for external scheduling. For Amazon S3, this requires a key and value for secret_access_key. For SFTP, this requires a key and value for password. */
  secret_parameters?: string | null
  /** Optional message to be included in scheduled emails */
  message?: string | null
}
