// This file is automatically generated based on the Looker Core API metadata.

export interface SessionConfig {
  /** Operations the current user is able to perform on this object */
  can: {[key: string]: boolean}
  /** Allow users to have persistent sessions when they login */
  allow_persistent_sessions: boolean
  /** Number of minutes for user sessions.  Must be between 5 and 43200 */
  session_minutes: number | null
  /** Allow users to have an unbounded number of concurrent sessions (otherwise, users will be limited to only one session at a time). */
  unlimited_sessions_per_user: boolean
  /** Enforce session logout for sessions that are inactive for 15 minutes. */
  use_inactivity_based_logout: boolean
  /** Track location of session when user logs in. */
  track_session_location: boolean
}

export interface RequestSessionConfig {
  /** Allow users to have persistent sessions when they login */
  allow_persistent_sessions?: boolean
  /** Number of minutes for user sessions.  Must be between 5 and 43200 */
  session_minutes?: number | null
  /** Allow users to have an unbounded number of concurrent sessions (otherwise, users will be limited to only one session at a time). */
  unlimited_sessions_per_user?: boolean
  /** Enforce session logout for sessions that are inactive for 15 minutes. */
  use_inactivity_based_logout?: boolean
  /** Track location of session when user logs in. */
  track_session_location?: boolean
}
