// This file is automatically generated based on the Looker Core API metadata.

export interface Snippet {
  /** Name of the snippet */
  name: string
  /** Label of the snippet */
  label: string
  /** SQL text of the snippet */
  sql: string
  /** Operations the current user is able to perform on this object */
  can: {[key: string]: boolean}
}

export interface RequestSnippet {

}
