// This file is automatically generated based on the Looker Core API metadata.

export interface SpaceDeletePlan {
  looks_to_delete_count: number | null
  dashboards_to_delete_count: number | null
  spaces_to_delete_count: number | null
}

export interface RequestSpaceDeletePlan {

}
