// This file is automatically generated based on the Looker Core API metadata.

export interface SqlQueryCreate {
  /** Name of the db connection on which to run this query */
  connection_name: string | null
  /** Name of LookML Model (this or `connection_id` required) */
  model_name: string | null
  /** SQL query */
  sql: string | null
  /** Visualization configuration properties. These properties are typically opaque and differ based on the type of visualization used. There is no specified set of allowed keys. The values can be any type supported by JSON. A "type" key with a string value is often present, and is used by Looker to determine which visualization to present. Visualizations ignore unknown vis_config properties. */
  vis_config: {[key: string]: any} | null
}

export interface RequestSqlQueryCreate {
  /** Name of the db connection on which to run this query */
  connection_name?: string | null
  /** Name of LookML Model (this or `connection_id` required) */
  model_name?: string | null
  /** SQL query */
  sql?: string | null
  /** Visualization configuration properties. These properties are typically opaque and differ based on the type of visualization used. There is no specified set of allowed keys. The values can be any type supported by JSON. A "type" key with a string value is often present, and is used by Looker to determine which visualization to present. Visualizations ignore unknown vis_config properties. */
  vis_config?: {[key: string]: any} | null
}
