// This file is automatically generated based on the Looker Core API metadata.

import { DBConnectionBase } from './db_connection_base'
import { UserPublic } from './user_public'

export interface SqlQuery {
  /** Operations the current user is able to perform on this object */
  can: {[key: string]: boolean}
  /** The identifier of the SQL query */
  slug: string
  /** Number of seconds this query took to run the most recent time it was run */
  last_runtime: number | null
  /** Number of times this query has been run */
  run_count: number
  /** Maximum number of rows this query will display on the SQL Runner page */
  browser_limit: number
  /** SQL query text */
  sql: string
  /** The most recent time this query was run */
  last_run_at: string | null
  /** Connection this query uses */
  connection: DBConnectionBase | null
  /** Model name this query uses */
  model_name: string | null
  /** User who created this SQL query */
  creator: UserPublic | null
  /** Explore page URL for this SQL query */
  explore_url: string | null
  /** Should this query be rendered as plain text */
  plaintext: boolean
  /** Visualization configuration properties. These properties are typically opaque and differ based on the type of visualization used. There is no specified set of allowed keys. The values can be any type supported by JSON. A "type" key with a string value is often present, and is used by Looker to determine which visualization to present. Visualizations ignore unknown vis_config properties. */
  vis_config: {[key: string]: any} | null
}

export interface RequestSqlQuery {
  /** Visualization configuration properties. These properties are typically opaque and differ based on the type of visualization used. There is no specified set of allowed keys. The values can be any type supported by JSON. A "type" key with a string value is often present, and is used by Looker to determine which visualization to present. Visualizations ignore unknown vis_config properties. */
  vis_config?: {[key: string]: any} | null
}
