// This file is automatically generated based on the Looker Core API metadata.

import { ProjectListItem } from './project_list_item'
import { StoryNavigationItem } from './story_navigation_item'

export interface Story {
  /** Unique Id */
  id: string
  title: string | null
  file_id: string | null
  project: ProjectListItem | null
  html: string | null
  navigation: StoryNavigationItem[] | null
}

export interface RequestStory {

}
