// This file is automatically generated based on the Looker Core API metadata.

import { ProjectListItem } from './project_list_item'

export interface StoryListItem {
  /** Operations the current user is able to perform on this object */
  can: {[key: string]: boolean}
  /** Unique Id */
  id: string
  title: string | null
  file_id: string | null
  project: ProjectListItem | null
}

export interface RequestStoryListItem {

}
