// This file is automatically generated based on the Looker Core API metadata.

export interface StoryNavigationItem {
  section: boolean
  me: boolean
  label: string | null
  url: string | null
}

export interface RequestStoryNavigationItem {

}
