// This file is automatically generated based on the Looker Core API metadata.

import { RequestThemeSettings, ThemeSettings } from './theme_settings'

export interface Theme {
  /** Operations the current user is able to perform on this object */
  can: {[key: string]: boolean}
  /** Timestamp for when this theme becomes active. Null=always */
  begin_at: string | null
  /** Timestamp for when this theme expires. Null=never */
  end_at: string | null
  /** Unique Id */
  id: number
  /** Name of theme. Can only be alphanumeric and underscores. */
  name: string
  /** Hash of name/value pairs for theme settings. These names get validated. */
  settings: ThemeSettings
}

export interface RequestTheme {
  /** Timestamp for when this theme becomes active. Null=always */
  begin_at?: string | null
  /** Timestamp for when this theme expires. Null=never */
  end_at?: string | null
  /** Name of theme. Can only be alphanumeric and underscores. */
  name?: string
  /** Hash of name/value pairs for theme settings. These names get validated. */
  settings?: RequestThemeSettings
}
