// This file is automatically generated based on the Looker Core API metadata.

import { RequestThemeSettings, ThemeSettings } from './theme_settings'

export interface ThemeValidator {
  /** Timestamp for when this theme becomes active. Null=always */
  begin_at: string | null
  /** Timestamp for when this theme expires. Null=never */
  end_at: string | null
  /** Unique Id */
  id: number
  /** Name of theme. Can only be alphanumeric and underscores. */
  name: string
  /** Hash of name/value pairs for theme settings. These names get validated. */
  settings: ThemeSettings | null
}

export interface RequestThemeValidator {
  /** Timestamp for when this theme becomes active. Null=always */
  begin_at?: string | null
  /** Timestamp for when this theme expires. Null=never */
  end_at?: string | null
  /** Unique Id */
  id?: number
  /** Name of theme. Can only be alphanumeric and underscores. */
  name?: string
  /** Hash of name/value pairs for theme settings. These names get validated. */
  settings?: RequestThemeSettings | null
}
