// This file is automatically generated based on the Looker Core API metadata.

export interface ThemeSettings {
  /** Default background color */
  background_color: string
  /** Base font size for scaling fonts */
  base_font_size: string | null
  /** Optional. ID of color collection to use with the theme. Use an empty string for none. */
  color_collection_id: string
  /** Default font color */
  font_color: string | null
  /** Primary font family */
  font_family: string
  /** Source specification for font */
  font_source: string | null
  /** Info button color */
  info_button_color: string
  /** Primary button color */
  primary_button_color: string
  /** Toggle to show filters. Defaults to true. */
  show_filters_bar: boolean
  /** Toggle to show the title. Defaults to true. */
  show_title: boolean
  /** Text color for text tiles */
  text_tile_text_color: string
  /** Background color for tiles */
  tile_background_color: string
  /** Text color for tiles */
  tile_text_color: string
  /** Color for titles */
  title_color: string
  /** Warning button color */
  warn_button_color: string
}

export interface RequestThemeSettings {
  /** Default background color */
  background_color?: string
  /** Base font size for scaling fonts */
  base_font_size?: string | null
  /** Optional. ID of color collection to use with the theme. Use an empty string for none. */
  color_collection_id?: string
  /** Default font color */
  font_color?: string | null
  /** Primary font family */
  font_family?: string
  /** Source specification for font */
  font_source?: string | null
  /** Info button color */
  info_button_color?: string
  /** Primary button color */
  primary_button_color?: string
  /** Toggle to show filters. Defaults to true. */
  show_filters_bar?: boolean
  /** Toggle to show the title. Defaults to true. */
  show_title?: boolean
  /** Text color for text tiles */
  text_tile_text_color?: string
  /** Background color for tiles */
  tile_background_color?: string
  /** Text color for tiles */
  tile_text_color?: string
  /** Color for titles */
  title_color?: string
  /** Warning button color */
  warn_button_color?: string
}
