// This file is automatically generated based on the Looker Core API metadata.

export interface ThinDataApp {
  id: string
  label: string | null
  js_url: string | null
  css_url: string | null
  is_extension: boolean
  path: string
}

export interface RequestThinDataApp {

}
