// This file is automatically generated based on the Looker Core API metadata.

export interface Timezone {
  /** Timezone */
  value: string | null
  /** Description of timezone */
  label: string | null
  /** Timezone group (e.g Common, Other, etc.) */
  group: string | null
}

export interface RequestTimezone {

}
