// This file is automatically generated based on the Looker Core API metadata.

export interface UserAttributeGroupValue {
  /** Operations the current user is able to perform on this object */
  can: {[key: string]: boolean}
  /** Unique Id of this group-attribute relation */
  id: number
  /** Id of group */
  group_id: number | null
  /** Id of user attribute */
  user_attribute_id: number | null
  /** If true, the "value" field will be null, because the attribute settings block access to this value */
  value_is_hidden: boolean
  /** Precedence for resolving value for user */
  rank: number | null
  /** Value of user attribute for group */
  value: string | null
}

export interface RequestUserAttributeGroupValue {

}
