// This file is automatically generated based on the Looker Core API metadata.

export interface UserLoginLockout {
  /** Operations the current user is able to perform on this object */
  can: {[key: string]: boolean}
  /** Hash of user's client id */
  key: string | null
  /** Authentication method for login failures */
  auth_type: string | null
  /** IP address of most recent failed attempt */
  ip: string | null
  /** User ID */
  user_id: number | null
  /** Remote ID of user if using LDAP */
  remote_id: string | null
  /** User's name */
  full_name: string | null
  /** Email address associated with the user's account */
  email: string | null
  /** Number of failures that triggered the lockout */
  fail_count: number | null
  /** Time when lockout was triggered */
  lockout_at: string | null
}

export interface RequestUserLoginLockout {

}
