// This file is automatically generated based on the Looker Core API metadata.

import { CredentialsApi3 } from './credentials_api3'
import { CredentialsEmail } from './credentials_email'
import { CredentialsEmbed } from './credentials_embed'
import { CredentialsGoogle } from './credentials_google'
import { CredentialsLDAP } from './credentials_ldap'
import { CredentialsLookerOpenid } from './credentials_looker_openid'
import { CredentialsOIDC } from './credentials_oidc'
import { CredentialsSaml } from './credentials_saml'
import { CredentialsTotp } from './credentials_totp'
import { Session } from './session'

export interface User {
  /** Operations the current user is able to perform on this object */
  can: {[key: string]: boolean}
  /** URL for the avatar image (may be generic) */
  avatar_url: string | null
  /** URL for the avatar image (may be generic), does not specify size */
  avatar_url_without_sizing: string | null
  /** API 3 credentials */
  credentials_api3: CredentialsApi3[] | null
  /** Email/Password login credentials */
  credentials_email: CredentialsEmail | null
  /** Embed credentials */
  credentials_embed: CredentialsEmbed[] | null
  /** Google auth credentials */
  credentials_google: CredentialsGoogle | null
  /** LDAP credentials */
  credentials_ldap: CredentialsLDAP | null
  /** LookerOpenID credentials. Used for login by Looker Analysts */
  credentials_looker_openid: CredentialsLookerOpenid | null
  /** OpenID Connect auth credentials */
  credentials_oidc: CredentialsOIDC | null
  /** Saml auth credentials */
  credentials_saml: CredentialsSaml | null
  /** Two-factor credentials */
  credentials_totp: CredentialsTotp | null
  /** Full name for display (available only if both first_name and last_name are set) */
  display_name: string | null
  /** EMail address */
  email: string | null
  /** (Embed only) ID of user's group space based on the external_group_id optionally specified during embed user login */
  embed_group_space_id: number | null
  /** First name */
  first_name: string | null
  /** Array of ids of the groups for this user */
  group_ids: number[] | null
  /** ID string for user's home space */
  home_space_id: string | null
  /** ID string for user's home folder */
  home_folder_id: string | null
  /** Unique Id */
  id: number
  /** Account has been disabled */
  is_disabled: boolean
  /** Last name */
  last_name: string | null
  /** User's preferred locale. User locale takes precedence over Looker's system-wide default locale. Locale determines language of display strings and date and numeric formatting in API responses. Locale string must be a 2 letter language code or a combination of language code and region code: 'en' or 'en-US', for example. */
  locale: string | null
  /** Array of strings representing the Looker versions that this user has used (this only goes back as far as '3.54.0') */
  looker_versions: string[] | null
  /** User's dev workspace has been checked for presence of applicable production projects */
  models_dir_validated: boolean | null
  /** ID of user's personal space */
  personal_space_id: number | null
  /** ID of user's personal folder */
  personal_folder_id: number | null
  /** User is identified as an employee of Looker */
  presumed_looker_employee: boolean
  /** Array of ids of the roles for this user */
  role_ids: number[] | null
  /** Active sessions */
  sessions: Session[] | null
  /** Per user dictionary of undocumented state information owned by the Looker UI. */
  ui_state: {[key: string]: string} | null
  /** User is identified as an employee of Looker who has been verified via Looker corporate authentication */
  verified_looker_employee: boolean
  /** User's roles are managed by an external directory like SAML or LDAP and can not be changed directly. */
  roles_externally_managed: boolean
  /** Link to get this item */
  url: string | null
}

export interface RequestUser {
  /** First name */
  first_name?: string | null
  /** ID string for user's home space */
  home_space_id?: string | null
  /** ID string for user's home folder */
  home_folder_id?: string | null
  /** Account has been disabled */
  is_disabled?: boolean
  /** Last name */
  last_name?: string | null
  /** User's preferred locale. User locale takes precedence over Looker's system-wide default locale. Locale determines language of display strings and date and numeric formatting in API responses. Locale string must be a 2 letter language code or a combination of language code and region code: 'en' or 'en-US', for example. */
  locale?: string | null
  /** User's dev workspace has been checked for presence of applicable production projects */
  models_dir_validated?: boolean | null
  /** Per user dictionary of undocumented state information owned by the Looker UI. */
  ui_state?: {[key: string]: string} | null
}
