// This file is automatically generated based on the Looker Core API metadata.

import { ValidationErrorDetail } from './validation_error_detail'

export interface ValidationError {
  /** Error details */
  message: string | null
  /** Error detail array */
  errors: ValidationErrorDetail[] | null
  /** Documentation link */
  documentation_url: string | null
}

export interface RequestValidationError {

}
