// This file is automatically generated based on the Looker Core API metadata.

export interface ValidationErrorDetail {
  /** Field with error */
  field: string | null
  /** Error code */
  code: string | null
  /** Error info message */
  message: string | null
  /** Documentation link */
  documentation_url: string | null
}

export interface RequestValidationErrorDetail {

}
