// This file is automatically generated based on the Looker Core API metadata.

export interface VisualizationManifest {
  /** Operations the current user is able to perform on this object */
  can: {[key: string]: boolean}
  /** Unique ID. */
  id: string
  /** ID to be used by the vis manager */
  vis_id: string
  /** Array of URLs the vis depends on. */
  dependencies: string[]
  /** Title of visualization */
  label: string
  /** Location of main visualization file. */
  main: string
  /** SRI hash corresponding to the 'main' uri. */
  main_sri_hash: string | null
  /** Flag indicating editability from the admin panel. */
  editable_in_admin_panel: boolean
  /** When the record was first created. */
  created_at: string | null
  /** When the record was last updated. */
  updated_at: string | null
}

export interface RequestVisualizationManifest {
  /** ID to be used by the vis manager */
  vis_id?: string
  /** Array of URLs the vis depends on. */
  dependencies?: string[]
  /** Title of visualization */
  label?: string
  /** Location of main visualization file. */
  main?: string
  /** SRI hash corresponding to the 'main' uri. */
  main_sri_hash?: string | null
  /** Flag indicating editability from the admin panel. */
  editable_in_admin_panel?: boolean
}
