// This file is automatically generated based on the Looker Core API metadata.

export interface WelcomeEmailTest {
  /** Operations the current user is able to perform on this object */
  can: {[key: string]: boolean}
  /** The content that will be sent as part of a custom welcome email */
  content: string | null
}

export interface RequestWelcomeEmailTest {
  /** The content that will be sent as part of a custom welcome email */
  content?: string | null
}
