// This file is automatically generated based on the Looker Core API metadata.

export interface WhitelabelConfiguration {
  /** Operations the current user is able to perform on this object */
  can: {[key: string]: boolean}
  /** Unique Id */
  id: number
  /** Customer logo image. Expected base64 encoded data (write-only) */
  logo_file: string | null
  /** Logo image url (read-only) */
  logo_url: string | null
  /** Custom favicon image. Expected base64 encoded data (write-only) */
  favicon_file: string | null
  /** Favicon image url (read-only) */
  favicon_url: string | null
  /** Default page title */
  default_title: string | null
  /** Boolean to toggle showing help menus */
  show_help_menu: boolean
  /** Boolean to toggle showing docs */
  show_docs: boolean
  /** Boolean to toggle showing email subscription options. */
  show_email_sub_options: boolean
  /** Boolean to toggle mentions of Looker in emails */
  allow_looker_mentions: boolean
  /** Boolean to toggle links to Looker in emails */
  allow_looker_links: boolean
}

export interface RequestWhitelabelConfiguration {
  /** Customer logo image. Expected base64 encoded data (write-only) */
  logo_file?: string | null
  /** Custom favicon image. Expected base64 encoded data (write-only) */
  favicon_file?: string | null
  /** Default page title */
  default_title?: string | null
  /** Boolean to toggle showing help menus */
  show_help_menu?: boolean
  /** Boolean to toggle showing docs */
  show_docs?: boolean
  /** Boolean to toggle showing email subscription options. */
  show_email_sub_options?: boolean
  /** Boolean to toggle mentions of Looker in emails */
  allow_looker_mentions?: boolean
  /** Boolean to toggle links to Looker in emails */
  allow_looker_links?: boolean
}
