// This file is automatically generated based on the Looker Core API metadata.

import { Project } from './project'

export interface Workspace {
  /** Operations the current user is able to perform on this object */
  can: {[key: string]: boolean}
  /** The unique id of this user workspace. Predefined workspace ids include "production" and "dev" */
  id: string
  /** The local state of each project in the workspace */
  projects: Project[] | null
}

export interface RequestWorkspace {

}
